### ISSUE TITLE
RC1

### ISSUE THREAD

**Issue by SebastianStehle** [OrleansContrib/OrleansDashboard#102]
Hi,

have you started to think about RC1? I thought I can make a simple PR, but so much stuff changed, e.g. IStatisticsPublisher and  ISiloMetricsDataPublisher are not supported anymore, but you can get access to them using the IManagerGrain.

**Comment by richorama** [comment]
No. I haven’t taken a look yet. Will get to it shortly, thanks for the heads up.

**Comment by richorama** [comment]
Oh, and PRs are very welcome!

**Comment by SebastianStehle** [comment]
Of course, I had the impression that it is a very big change and that it might make more sense when you try to handle this part. But I can help with the new configuration model.

**Comment by richorama** [comment]
I've started looking, there seems to be quite a few changes...

**Comment by SebastianStehle** [comment]
Do you need help?

**Comment by SebastianStehle** [comment]
I see no option right now, to retrieve the counters.

**Comment by SebastianStehle** [comment]
Sorry, was wrong, you can write a ITelemetryProducer  for that.

**Comment by SebastianStehle** [comment]
See: https://github.com/OrleansContrib/OrleansDashboard/pull/104

**Comment by SebastianStehle** [comment]
Just noticed that this line is wrong: https://github.com/OrleansContrib/OrleansDashboard/blob/master/OrleansDashboard/GrainProfiler.cs#L87

Because Stopwatch.Ticks != DateTime.Ticks (== TimeSpan.Ticks)

https://msdn.microsoft.com/en-us/library/system.diagnostics.stopwatch.elapsedticks.aspx

**Comment by richorama** [comment]
Awesome work, thanks @SebastianStehle

**Comment by SebastianStehle** [comment]
NP, I love this project :)
