### ISSUE TITLE
Orleans 2.0 cannot find grain implementation class when using Dashboard

### ISSUE THREAD

**Issue by dandago** [OrleansContrib/OrleansDashboard#118]
I'm getting this exception when the Orleans Dashboard is configured with 2.0:

![image](https://user-images.githubusercontent.com/13241564/38521781-92788ccc-3c3e-11e8-947e-62c160017368.png)

If I comment out `UseDashboard(...)`, it runs just fine. The dashboard seems to be somehow interfering with grain resolution.

Repro project attached.

[Orleans2GettingStarted.zip](https://github.com/OrleansContrib/OrleansDashboard/files/1891725/Orleans2GettingStarted.zip)

**Comment by richorama** [comment]
Thanks for reporting @dandago, looking into it now...

**Comment by richorama** [comment]
Fixed in version 2.0.0 (PR #119)

**Comment by richorama** [comment]
...although I notice that reminders are returning a 500. I'll investigate that.
