### ISSUE TITLE
Dashboard shows an error (500) when Reminders are not enabled

### ISSUE THREAD

**Issue by richorama** [OrleansContrib/OrleansDashboard#120]
version 2.0.1

**Comment by dandago** [comment]
Just curious since I observed this problem too, what was the root cause?

**Comment by richorama** [comment]
When the storage for reminders is not configured, any grain which has the IRemindersTable (or similar) service as an argument on the constructor will not get activated. This was the case for the grain the dashboard uses to read the reminders.
