### ISSUE TITLE
UnobservedTaskException caught by silo when Dashboard is present

### ISSUE THREAD

**Issue by NicolaAtorino** [OrleansContrib/OrleansDashboard#123]
Hi everyone,
first of all thanks for your amazing contribution to the project.
I am seeing a strange issue with the orleans dashboard : even if the dashboard and the cluster itself works fine, my silo is catching a lot of unobservedexceptions. If i remove the dashboard, the exceptions are gone. This are the messages i find in my logs : 

`[2018-04-17 13:12:04.094 GMT     2	ERROR  	100005	UnobservedExceptionHandler	10.15.111.14:20003]	!!!!!!!!!! UnobservedExceptionsHandlerClass Caught an UnobservedTaskException event sent by [Id=4410948, Status=Faulted]. Exception = 
Exc level 0: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.
Exc level 1: System.Threading.Tasks.TaskCanceledException: The request was aborted	`

`[2018-04-17` 13:12:04.094 GMT     2	ERROR  	100102	Silo	10.15.111.14:20003]	!!!!!!!!!! Silo caught an UnobservedException with context==null.	
Exc level 0: System.Threading.Tasks.TaskCanceledException: The request was aborted	`

`Silo caught an UnobservedException with context==null.`

this exceptions happens more than 60 times per minute.

more rarely, i can find this in my logs : 

`UnobservedExceptionsHandlerClass Caught an UnobservedTaskException event sent by [Id=4408717, Status=Faulted]. Exception = 
Exc level 0: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.
Exc level 1: System.IO.IOException: Error -4077 ECONNRESET connection reset by peer
Exc level 2: Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4077 ECONNRESET connection reset by peer`

I could not find any more information.

Both Orleans and OrleansDashboard version is 1.5.3 .
Libuv version is : "Libuv.1.9.1" runtime win7-x86 .

Any clue on what this could be?

Thank you very much.

**Comment by richorama** [comment]
Thanks for reporting @NicolaAtorino , I'll take a look in the next day or two.

**Comment by richorama** [comment]
I have had a play around, and I'm unable to reproduce. Are you able to share any of your code, or provide a minimum example?
