### ISSUE TITLE
Build fails when OrleansDashboard is combined with F# and paket

### ISSUE THREAD

**Issue by Karamell** [OrleansContrib/OrleansDashboard#124]
Using F# and with the [paket](https://fsprojects.github.io/Paket/index.html) dependency manager somehow triggers codegeneration errors in the silo build. 

```FSC : error FS0226: The file extension of 'obj\Debug\netcoreapp2.0\SiloHost.orleans.g.cs' is not recognized. Source files must have extension .fs, .fsi, .fsx, .fsscript, .ml or .mli. [C:\Users\n23130\src\orleanspaket\src\SiloHost\SiloHost.fsproj]```

It's the combination of paket at OrleansDashboard that will trigger the generation of the file `SiloHost.orleans.g.cs`. Remove any of the two and everything works again.

I've demoed the build error here: https://github.com/Karamell/orleanspaket

**Comment by richorama** [comment]
Thanks for reporting this @Karamell and for providing a sample.

I think you're running into this problem: http://dotnet.github.io/orleans/Documentation/Advanced-Concepts/Codegen.html#during-build

```
The Microsoft.Orleans.OrleansCodeGenerator.Build package only supports C# projects. Other languages are supported either using the Microsoft.Orleans.OrleansCodeGenerator package described below, or by creating a C# project which can act as the target for code generated from assemblies written in other languages.
```

One possible quick fix might be to remove the `Microsoft.Orleans.OrleansCodeGenerator.Build` package.

A longer term fix would be for the dashboard to support both codegen methods, I'll look into this.

**Comment by Karamell** [comment]
Hi thanks for answering so fast
I am not referencing the `Microsoft.Orleans.OrleansCodeGenerator.Build`. The project is _not_ configured for compile time codegen.

- If I remove `OrleansDashboard` the build works.
- If I replace paket with nuget the build works.

I hoped to be able to combine the two. The quick fix for me is to not use paket.

**Comment by Karamell** [comment]
Another fix is to remove `Microsoft.Orleans.OrleansCodeGenerator.Build` from `OrleansDashboard.nuspec`. Is it really a required dependency?

**Comment by richorama** [comment]
I have just tried switched to code gen at initialisation and it didn't work.

```
Unhandled Exception: Orleans.Runtime.OrleansConfigurationException: None of the assemblies added to ApplicationPartManager contain generated code. Ensure that code generation has been executed for grain interface and class assemblies.
   at Orleans.Configuration.Validators.ApplicationPartValidator.ValidateConfiguration()
   at Orleans.ClientBuilder.ValidateSystemConfiguration(IServiceProvider serviceProvider)
   at Orleans.ClientBuilder.Build()
   at TestHost.Program.Main(String[] args) in c:\Users\richa\Code\OrleansDashboard\TestHost\Program.cs:line 43
```
...I'll have more of a play.

**Comment by richorama** [comment]
There's an update in #128 which may fix this problem. I haven't released to nuget yet, but you can get the package from here: https://ci.appveyor.com/project/richorama/orleansdashboard/build/artifacts
