### ISSUE TITLE
【2.0.1】What is the problem? Has been reporting an error?

### ISSUE THREAD

**Issue by AClumsy** [OrleansContrib/OrleansDashboard#126]
What is the problem? Has been reporting an error?
![bxetiz rc0e etbnk hoi6n](https://user-images.githubusercontent.com/28291464/39397177-a1108746-4b2d-11e8-87f0-a656eb8e0d2e.png)

**Comment by aqa510415008** [comment]
This error may be caused by this problem [Orleans-4178](https://github.com/dotnet/orleans/issues/4178)

**Comment by aqa510415008** [comment]
@richorama It seems that I have found a problem, which is the reason I mentioned above.
