### ISSUE TITLE
Ability to filter out Dashboard grains

### ISSUE THREAD

**Issue by jkonecki** [OrleansContrib/OrleansDashboard#127]
Dashboard grains are included in all the charts / statistics.
I would like to have the ability to exclude them so I can see the metrics for my application only.

**Comment by jkonecki** [comment]
I would prefer a switch in the website so I can enable / disable at runtime.

Regex filter would be nice but I would put it as lower priority. TBH,
ability to sort the grains table by clicking on the header would be more
useful.

**Comment by richorama** [comment]
Thanks Jakub.
