### ISSUE TITLE
v1.5 - CPU overhead reported at ~10-20%

### ISSUE THREAD

**Issue by richorama** [OrleansContrib/OrleansDashboard#130]
Presents when the dashboard is installed, even when the UI is not running, but only on one node (the one hosting the dashboard grain).

**Comment by SebastianStehle** [comment]
The Dashboard Grain does probably not use the best data structures, we would need something like a LRUCache instead.

**Comment by richorama** [comment]
true, we could probably optimise here. although I don't _think_ that there is a huge amount of data in these structures...

**Comment by SebastianStehle** [comment]
Depends, if you have 1000 calls per second you would  have at least 100.000 entries.

**Comment by richorama** [comment]
The `history` List will have `100 * SiloCount * GrainMethodCount` entries, which could get you up into the 100,000s range.

**Comment by SebastianStehle** [comment]
True, have forgotten that they are already aggregated by the interceptor.

**Comment by SebastianStehle** [comment]
One improvement could be to store all incoming GrainCallEntry's to an internal list and then use a timer/reminder to aggregate these entries into the main history list. It would probably save a lot of allocations, because the list has to be restructured all the time. Also a LinkedList could help. The performance would be more stable if you add more Silos.

**Comment by SebastianStehle** [comment]
Wouldnt it easier to maintain a dictionary of unique Silo-Methods instead of all the stuff in the Report method?

**Comment by jkonecki** [comment]
The improvements to the data structures / calculations would definitelly be helpful, but I don't think this is an underlying root of the issue. The calls are reported by dashboard as taking 40-50ms in my case and don't really explain 100% CPU usage on a single vCPU when hosted in Azure.

**Comment by SebastianStehle** [comment]
But what else could it be?

**Comment by jkonecki** [comment]
I couldn't see anything obvious when looking at performance results (https://files.gitter.im/dotnet/orleans/qXWn/image.png - with dashboard on left, without on right)
Maybe the way the timings are called / reported (interceptor)? That would explain the slowdown even when UI is not querying.

**Comment by jkonecki** [comment]
The same slowdown was reported in 2.0:

@bboyle1234

> 
> It's a docker container on a windows machine, everything is stock standard. So we've got Docker for Windows, running a linux VM on Hyper-V Manager, default settings. The container itself is built FROM microsoft/dotnet:2.0-runtime. I got my cpu usage by the command docker stat [containerName]. The single-silo cluster has approximately 100 grains and 100 streams, passing about 70 messages per second between grains and 70 messages per second into streams. With dashboard, cpu usage hovered between 50% - 75%, with the usual bell (normal) curve distribution centered at 65%. With dashboard removed, the bell curve centered on 45%.
> We run 8 x azure 4CPU vms

**Comment by richorama** [comment]
I'm thinking of extracting out the metrics collection into a separate class/classes which can be unit tests and micro benchmarked more easily.

I also think we should be able to turn parts of the dashboard on/off by configuration to help diagnose these kinds of fault.

**Comment by jkonecki** [comment]
> My suspicion was a threading issue, but I haven't got an environment that can reproduce the results. If I get time I'll spin up a single core VM and see...
Richard, you may try setting process affinity to 1 or 2 cores in Task Manager. You will see the difference in CPU usage clearly.

**Comment by richorama** [comment]
#142 might make some difference to the 1.5 branch

**Comment by jkonecki** [comment]
I did some non-scientific tests with #142 and I cannot see any meaningful improvement :-(
TestHost project (with affinity set to the first 2 cores) - left with dashboard enabled, right without. (No UI running at all)

![image](https://user-images.githubusercontent.com/1775247/39783493-2e345c06-530d-11e8-979a-5af220853602.png)

**Comment by richorama** [comment]
@jkonecki thanks for testing. I'm also trying it now.

The TestHost.exe does apply a load to the system using a single thread. When I disable this load I see the CPU utilisation fall from ~50% to ~20%.

**Comment by richorama** [comment]
I have done some profiling work. 

There is a performance hit with the dashboard doing continuous data sampling. It asks the management grain and other services for metrics on a 1 second timer.

I'm thinking of slowing down the sample rate for some of the counters, it seems to me that activation counts and silo health don't need to be sampled every second.

**Comment by jkonecki** [comment]
Is this something which we could enable / disable from the UI?

Jakub

**Comment by richorama** [comment]
Perhaps. An easier first step would be to provide some config in C#.

**Comment by SebastianStehle** [comment]
In 2.0 we already have this setting. We should benchmark it there first.
