### ISSUE TITLE
Integrate with MetricTracker

### ISSUE THREAD

**Issue by richorama** [OrleansContrib/OrleansDashboard#14]
Investigate using [MetricTracker](https://github.com/OrleansContrib/Orleans.TelemetryConsumers.MetricsTracker) to capture telemetry data.

**Comment by richorama** [comment]
Waiting for MetricTracker to leave beta.

https://www.nuget.org/packages/Orleans.TelemetryConsumers.MetricsTracker/

**Comment by talarari** [comment]
Seems like it left beta

**Comment by SebastianStehle** [comment]
@richorama Can we close this?
