### ISSUE TITLE
One of the silo show memory usage -50%

### ISSUE THREAD

**Issue by zhangalei** [OrleansContrib/OrleansDashboard#140]
orleans 1.5.x, 2 silos, One of the silo show memory usage -50%, the other looks normal.

![image](https://user-images.githubusercontent.com/30083114/39719105-d5c7e2aa-51fd-11e8-867f-31755107bbe8.png)

![image](https://user-images.githubusercontent.com/30083114/39719172-0af5a3d6-51fe-11e8-9861-0553c8e34e48.png)

**Comment by richorama** [comment]
quite impressive! I'm guess that memory available exceeds Int32.MaxValue I'll investigate.

Thank you for reporting.
