### ISSUE TITLE
Show grain exceptions on the graph

### ISSUE THREAD

**Issue by richorama** [OrleansContrib/OrleansDashboard#15]

**Comment by danvanderboom** [comment]
These could be red lines or thin blocks, some very simple visualization of exceptions thrown from grain methods. Some counters or metrics like number of exceptions so far, number of exceptions/second or exceptions/minute, etc. would be good to see, even some kind of chart showing moving average over time of exception frequency... per grain method, overall per grain type, or across the whole system.
