### ISSUE TITLE
Dashboard is not working when not hosted on /

### ISSUE THREAD

**Issue by michaelgeorgeattard** [OrleansContrib/OrleansDashboard#153]
Hi,

I hosted as `https://host.com/dashboard` and neither JS resources, nor AJAX call URLs are correct.

I modified `baseHref` to `"https://host.com/dashboard/"` and changed script src from `/index.min.js` to `index.min.js`, and the application more or less worked (apart from `/version` request).

Is support for hosting on something apart from `/` in the backlog please?

**Comment by richorama** [comment]
commit 1f8fa4a8296dfa81758a18a8dd8a6cf3112d8625 removes the slash from the `/version` request.

I have also adjusted the favicon links.

I have tried this out on the `TestHostSeparate` project, and it seems to work.

If you need this urgently on nuget I can make a release.

**Comment by SebastianStehle** [comment]
Favicons only work on the root level anyway, I think.
