### ISSUE TITLE
Grain state output

### ISSUE THREAD

**Issue by bboyle1234** [OrleansContrib/OrleansDashboard#156]
Get a list of all the ids of activated grains of a particular grain type.
Select a single grain id to get information about the grain.
Get a json output of the grain's current state?
Get json output of parameterless grain method calls.

**Comment by richorama** [comment]
Thanks @bboyle1234 for suggesting these ideas.

I'm curious to hear what other people think of these suggestions. They sound extremely useful, my only hesitation is that they're at odds with one of my original objectives with the dashboard, which was to provide aggregated metrics of runtime performance, and not go down to the individual grain level.

However, I think my objective is probably out of date, and as long as it's a feature we can turn on/off I don't see it having any impact on usability or performance.

Would you propose that on the page that displays information about a grain type, it's possible to get to another page which lists the keys for the activations of these grains?

From there you could select one, and inspect the state and call methods?

**Comment by bboyle1234** [comment]
Exactly

**Comment by bboyle1234** [comment]
Another idea: Collecting stats on grain state write times.

**Comment by bboyle1234** [comment]
Hi @richorama  :)
I'm going to need many of these features soon. Either I'll be coding them in my own (amateurish hacky) way in my grains, or I might be able to code them under your tutelage into the dashboard. Would you like be able to give me some idea of where you're at on this, and whether you might be able to guide me along in upgrading the dashboard?

**Comment by richorama** [comment]
Hi @bboyle1234 ,

I'm very happy to help to get you started and to help you implement these features.

Could I suggest you shortlist the features you'd like to tackle, or prioritise them, then we can create an issue for each.

We perhaps we could then have a video call to help you get started. Would be nice to open this to anyone interested in contributing.

**Comment by bboyle1234** [comment]
Hi @richorama, I created a separate issue for the stats ideas yesterday. This thread can be for the grain state ideas listed in my first post. 
I suspect I'll be wanting to start work on this in about a week from now.
Thank you for your offer, much appreciated.

**Comment by leonardosimoura** [comment]
Hi all,
i made a PR to get the state from grain and a found this issue, so i think is better keep this one...

The ideia is to add a inital support for this with a list of activations ids and a view of current state(details in PR)

PR:  #360 

Let me know if you have any suggestions.
