### ISSUE TITLE
Cannot load IDashboardGrain when deployed to Azure

### ISSUE THREAD

**Issue by DixonDs** [OrleansContrib/OrleansDashboard#16]
I get the following error:
```
[2016-10-18 13:24:37.357 GMT    52	ERROR  	103109	ProviderLoader/IBootstrapProvider	10.220.7.4:11111]	!!!!!!!!!! Exception initializing provider Name=Dashboard Type=[Dashboard, OrleansDashboard.Dashboard]	
Exc level 0: System.InvalidOperationException: Cannot find generated GrainReference class for interface 'OrleansDashboard.IDashboardGrain'
   at Orleans.GrainFactory.MakeCaster(Type interfaceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Orleans.GrainFactory.Cast(IAddressable grain, Type interfaceType)
   at Orleans.GrainFactory.Cast[TGrainInterface](IAddressable grain)
   at OrleansDashboard.Dashboard.Init(String name, IProviderRuntime providerRuntime, IProviderConfiguration config)
   at Orleans.Providers.ProviderLoader`1.<InitProviders>d__7.MoveNext()
```

Any ideas what could be wrong or how can I track the source of the issue?

**Comment by richorama** [comment]
Hi @DixonDs,

Can you confirm that the DLL is deployed on to the Azure machine? It looks like it can't find it...

**Comment by richorama** [comment]
Ignore that, you can see quite clearly from the stack trace that it can find the bootstrap provider, it just isn't loading the grain implementation.. Not sure why..

**Comment by DixonDs** [comment]
I have a suspicion that it has something to do with bootstrap load order since I use DI to load grain implementations, so maybe that happens on the later stage than bootstraper `Init` method called. But it is just a speculation.

**Comment by richorama** [comment]
AFAIK the grains are registered first. I wonder whether the DLL isn't on the load path for grains..

**Comment by jdom** [comment]
Are you sure that dashboard project has the build time codegen package installed? Otherwise it will rely on the host project to have runtime codegen enabled (which is optional). 
The other likely issue is if not all of Orleans packages where not updated to 1.3.0, as mismatched versions currently don't work well with each other

**Comment by richorama** [comment]
Thanks @jdom,

The codegen appears to be included : https://github.com/OrleansContrib/OrleansDashboard/blob/master/OrleansDashboard/packages.config#L9

**Comment by DixonDs** [comment]
@richorama I was able to reproduce the issue locally in Azure emulator. Then I replaced the nuget package with the source project directly - the issue was still reproducible. But once I've added the following lines (copied from my grain interfaces project) to the `OrleansDashboard.csproj`, the issue has gone:
```
<Import Project="..\packages\Microsoft.Orleans.OrleansCodeGenerator.Build.1.3.0\build\Microsoft.Orleans.OrleansCodeGenerator.Build.targets" Condition="Exists('..\packages\Microsoft.Orleans.OrleansCodeGenerator.Build.1.3.0\build\Microsoft.Orleans.OrleansCodeGenerator.Build.targets')" />
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\packages\Microsoft.Orleans.OrleansCodeGenerator.Build.1.3.0\build\Microsoft.Orleans.OrleansCodeGenerator.Build.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Microsoft.Orleans.OrleansCodeGenerator.Build.1.3.0\build\Microsoft.Orleans.OrleansCodeGenerator.Build.targets'))" />
  </Target>
```

**Comment by DixonDs** [comment]
In result I've resolved the issue just by adding `Microsoft.Orleans.OrleansCodeGenerator` package to the host project.
