### ISSUE TITLE
Reduce cpu workload when dashboard is not being viewed

### ISSUE THREAD

**Issue by bboyle1234** [OrleansContrib/OrleansDashboard#160]
Since the dashboard seems to be fairly intensive, cpu-wise, I thought it might be a good idea to deactivate its workload when there are no administrators actually viewing dashboard pages. 
To handle situations where an administrator leaves the dashboard tab open in their browser overnight, it might be a good idea to automatically (if configured) stop serving a dashboard session after a few minutes, until user action starts it up again.

**Comment by SebastianStehle** [comment]
What exactly is CPU intensive?

**Comment by bboyle1234** [comment]
My grain methods typically take half a millisecond to execute. 
I've seen the dashboard grain requests in the DashBoard grain that occur every second from the browser take about a second to complete, according to statistics shown on the Dashboard.
I imagine the 1-second delay is due to cpu work rather than IO operations.
I'll catch a screenshot when I see it again and post it here.

**Comment by SebastianStehle** [comment]
I think there is still a lot of potential for improvements. We have lots of allocations and O(n) loops. We can also use a faster json serializer.

**Comment by richorama** [comment]
Very happy to consider any suggestions for perf improvements. I would encourage a 'scientific' approach with some benchmarking.
