### ISSUE TITLE
Stat collection ideas

### ISSUE THREAD

**Issue by bboyle1234** [OrleansContrib/OrleansDashboard#161]
Grain state read and write times.
Grain activation and deactivation times.
Recent Orleans errors / warnings.

**Comment by richorama** [comment]
Great ideas. AFAIK we're missing the hooks to allow us to collect activation/deactivation times, but perhaps the dashboard could provide a service to allow your grain code to submit these metrics, until a better approach is available.

The current grain profiling code could be tweaked to record error types.
