### ISSUE TITLE
Orleans logger output

### ISSUE THREAD

**Issue by bboyle1234** [OrleansContrib/OrleansDashboard#162]
Would it be possible to capture and display output generated by the Orleans loggers?
Or ... would it be possible to create a logger whose output is displayed in the dashboard, and make that available to the user for injection.
That way, the entire logger output for each silo would be available via the Orleans dashboard.

**Comment by bboyle1234** [comment]
Or perhaps, one would be able to view grain-specific logs ... i dunno, just thinking out loud ... we're already viewing logs in the traditional manner, I'm not sure if anyone thinks this is a good idea. I'm not sure myself!

**Comment by SebastianStehle** [comment]
I think the most people will use a logging infrastructure anyway, like ELK stack or Stackdriver.

**Comment by bboyle1234** [comment]
Wow - just saw Stackdriver for the first time - it's what I've been looking for all my life haha! Awesome!
