### ISSUE TITLE
Dashboard blocks all other TelemetryConsumers

### ISSUE THREAD

**Issue by justmara** [OrleansContrib/OrleansDashboard#164]
[this line](https://github.com/OrleansContrib/OrleansDashboard/blob/master/OrleansDashboard/ServiceCollectionExtensions.cs#L37) is a problem.
We have our own telemetryconsumer:
```
services.Configure<TelemetryOptions>(options => options.AddConsumer<InfluxDb>());
```
After adding Dashboard our consumer is never instantiated and metrics are not propagated. This happens because `DashboardTelemetryProducer` overrides default `ITelemetryProducer`'s realization TelemetryManager, that were propagating events to consumers. Maybe better switch it to `ITelemetryConsumer` so it could live side-by-side with others
I mean you could listen to metrics without intercepting 'em.

**Comment by SebastianStehle** [comment]
Can you make a PR?

**Comment by justmara** [comment]
here is one :)

**Comment by SebastianStehle** [comment]
Thank you. I tested it and incremented the version. You should see a new version on nuget.org soon.
