### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by Kimserey** [OrleansContrib/OrleansDashboard#169]
The current instantiation of the Kestrel host when the dashboard is selfhosted does not seem to provide a way to configure HTTPS.

Are there any plan for HTTPS support or are there any recommendations?

**Comment by richorama** [comment]
Hi @Kimserey,

No plans to support HTTPS at the moment. If you look at the TestHostSeparate project you can see how you can start the kestrel host yourself, and add the dashboard as middleware: 

https://github.com/OrleansContrib/OrleansDashboard/blob/master/TestHostSeparate/Program.cs

This then gives you full control to add HTTPS, or whatever you want.

**Comment by Kimserey** [comment]
Thanks!
