### ISSUE TITLE
ClusterStats API response has inconsistent number of data points

### ISSUE THREAD

**Issue by carloslazo** [OrleansContrib/OrleansDashboard#176]
ClusterStats fluctuates between 100 and 101 data points. This behavior can be visually seen in all the graphs once it populates the data point entries to 100.

**Comment by SebastianStehle** [comment]
I cannot reproduce it. 

@richorama Can you reproduce it or shall we just delete it? Perhaps something old.

**Comment by SebastianStehle** [comment]
I was wrong. I can reproduce it. I think the whole implementation is buggy, because the it does not return the stats for the last 100 seconds, but the last stats within the last 100 seconds. So If there are data points missing in between, the whole graph fluctuates.
