### ISSUE TITLE
Dashboard doesn't work on 4.6.2

### ISSUE THREAD

**Issue by matteofabbri** [OrleansContrib/OrleansDashboard#183]
Dashboard relays on Kestrel which relays on Libuv which sadly at the moment doesn't work on 4.6.2
Same issue on both packages 

Libuv.1.0.0 - No reference is added to project, when is added it fails at runtime
OrleansDashboard.Libuv.1.0.0 - Failed to add reference to 'libuv'. Please make sure that the file is accessible, and that it is a valid assembly or COM component.				

How to reproduce:
Checkout the simplest Orleans project:
https://github.com/dotnet/orleans/tree/master/Samples/2.0/HelloWorld

Install OrleansDashboard on SiloHost and see it works fine.

Add a new 4.6.2 project  in the solution, add requested references, copy the code from SiloHost and try to run.

**Comment by richorama** [comment]
Thanks for reporting this @matteofabbri 

I'm not really sure how to progress this, given that it's an upstream problem.

**Comment by SebastianStehle** [comment]
Good to know. But you can just host it by yourself. There is a sample for that and it is just 20 lines of code or so.
