### ISSUE TITLE
add virtual streams to the dashboard

### ISSUE THREAD

**Issue by danvanderboom** [OrleansContrib/OrleansDashboard#19]
Virtual streams would be a good thing to monitor. Which grains or grain methods are publishing messages to which virtual streams? How frequently are messages being published to each of the virtual streams?

I imagine a list of virtual streams like grain methods all on a page together, with message publish events visualized in the time-series chart, with metrics for number of messages published per second, etc.

If there are large numbers of virtual streams, some way to aggregate them, organize them in a tree/outline, etc., would likely be needed. I don't have all the answers, I just think it would be great to see activity on our virtual streams.

Any ideas?

**Comment by danvanderboom** [comment]
Track average and total number of bytes/KB for messages sent via each stream. See where the bulk of data is flowing through the system via streams. See when that rises and falls, during various interactions in automated tests, etc.

**Comment by alexanderdevoid** [comment]
@danvanderboom Since grain activations can be migrated we would also need to have this data differentiated per silo that the activation was a part of at some point.

This way we can see how each activation contributed to bandwidth consumption of our cluster members.

**Comment by Cloud33** [comment]
It's a great feature.

**Comment by koenbeuk** [comment]
Stream interceptors, if ever implemented, could help in implementing this feature: https://github.com/dotnet/orleans/issues/7394

**Comment by richorama** [comment]
I don't believe it is currently possible to implement this feature.
