### ISSUE TITLE
Special characters in grain names causing issues

### ISSUE THREAD

**Issue by michaelgeorgeattard** [OrleansContrib/OrleansDashboard#191]
Given a grain with name: `ContentEntityGrain<TranslationContentModel>`, I am getting `No messages recorded` when going to grain page.

Replicated in `OrleansDashboard` version `2.0.9`.

**Comment by richorama** [comment]
Thanks for reporting this. I do have some tests for grains that use generics. I'll attempt to replicate.

**Comment by richorama** [comment]
I can reproduce this fault. I'll take a look at fixing it shortly.
