### ISSUE TITLE
Is there a dashboard center? All orleans host's data are displayed on a centralized site.

### ISSUE THREAD

**Issue by sundong1982** [OrleansContrib/OrleansDashboard#196]
Is there a dashboard center? All orleans host's data are displayed on a centralized site.

**Comment by richorama** [comment]
Hi @sundong1982 thanks for your question. I'm a little confused about what you're asking. There is a page that lists all silos participating in the cluster. Is that what you needed?

**Comment by sundong1982** [comment]
I hope to collect all the silo information of different ClusterId.

**Comment by richorama** [comment]
The dashboard only reports on the cluster it is hosted within. To see the data for a different cluster, you can connect it's own dashboard.

The dashboard does not support multi-cluster configurations.

**Comment by matteofabbri** [comment]
We were thinking a kinda similar changes here at the office where we use it.
Splitting computation part and the actual gui to make have one single web application where is possible to monitor all ours clusters

**Comment by sundong1982** [comment]
My system with many services, opening their respective dashboard to see it very troublesome.

**Comment by richorama** [comment]
It would be a nice feature. Any thoughts on how this would work are very welcome.

**Comment by matteofabbri** [comment]
@sundong1982 I started to implement it, is relative easy.
Here a working initial stub https://github.com/matteofabbri/OrleansDashboard/tree/master/OrleansDashboard.Center

**Comment by SebastianStehle** [comment]
I would just host the dashboard in all your clusters and create a simple html page with a few iframes ;) ... Perhaps we could an option to hide the header or so.

**Comment by sundong1982** [comment]
> @sundong1982 I started to implement it, is relative easy.
> Here a working initial stub https://github.com/matteofabbri/OrleansDashboard/tree/master/OrleansDashboard.Center

thx :)

**Comment by sundong1982** [comment]
@richorama thx:)

**Comment by richorama** [comment]
@matteofabbri your fork is very interesting. It would be good to discuss how we can migrate the functionality upstream.

**Comment by matteofabbri** [comment]
@richorama thanks, for what i see is very easy to develop a web interface to integrate the dashboard into a generic website but after many tries i can say i have no idea oin how to make it generic
