### ISSUE TITLE
display version of Orleans host with silo identifier

### ISSUE THREAD

**Issue by danvanderboom** [OrleansContrib/OrleansDashboard#21]
It would be nice to see what the .NET assembly version is for each silo's Orleans host, to tell at a glance whether all silos are running the same version or not.

**Comment by richorama** [comment]
Good idea.  Do you know how to get the Orleans version?

**Comment by danvanderboom** [comment]
I was thinking the version of the solution-specific OrleansHost assembly, but version of Orleans would also be useful. Regardless of which Orleans version is referenced by OrleansDashboard, there should be just one version of Orleans assemblies loaded, based on what the main app has specified, right? If that's the case, an expression like this should work:

`typeof(Orleans.Runtime.SiloAddress).Assembly.GetName().Version`

For the version of the Orleans host service app:

`System.Reflection.Assembly.GetEntryAssembly().GetName().Version`
