### ISSUE TITLE
Dashboard Silo won't die.

### ISSUE THREAD

**Issue by PGP-Protector** [OrleansContrib/OrleansDashboard#210]
I'm probably doing something wrong, but this is the issue / bug I'm having.

Using ADO Net Clustering, I can start multiple Silos in my cluster Without Dashboard running.
They spin up find.

If I then have a call that start a Dashboard only silo like this.
`                
`ISiloHostBuilder layoutSilo = new SiloHostBuilder()
`    .Configure<ProcessExitHandlingOptions>(options => options.FastKillOnProcessExit = false)`
`    .UseDashboard(options => { })`
`    .Configure<ClusterOptions>(options => { options.ClusterId = dashboardConfig.ClusterId; options.ServiceId = dashboardConfig.ServiceId; })`
`    .Configure<ClusterMembershipOptions>(options => { options.ValidateInitialConnectivity = false; options.ExpectedClusterSize = 1; })`
`    .Configure<SiloOptions>(Options => Options.SiloName = "Dashboard")`
`    .Configure<EndpointOptions>(options => { options.GatewayPort = Gateway; options.SiloPort = Port; options.AdvertisedIPAddress = IPAddress.Loopback; })`
`    .ConfigureLogging(logging => { logging.SetMinimumLevel(Microsoft.Extensions.Logging.LogLevel.Error); logging.AddNLog(); });`
`if (dashboardConfig.ClusteringMode == "ADO")`
`    {`
`    layoutSilo.UseAdoNetClustering(options => { options.ConnectionString = dashboardConfig.AdoNetClusteringConnectionString; options.Invariant = dashboardConfig.AdoNetClusteringInvariant; });`
` }`
`  else`
`{`
`    layoutSilo.UseLocalhostClustering();`
`}`
`     DashboardSilo = layoutSilo.Build();`
`DashboardSilo.StartAsync().Wait();`

My Dashboard Silo will start up as expected (so far so good)

Then when I'm done using the Dashboard I try to stop the above Silo.
`try`
`{`
`    Console.WriteLine($"Sending Stop to Dashboard");`
`    DashboardSilo.StopAsync().Wait();`
`    Console.WriteLine($"Dashboard Stopped");`
`    DashboardSilo.Dispose();`
`}`
`catch (Exception ex)`
`{`
`    Console.WriteLine($"Exception {ex.Message} when shutting down Dashboard");`
`}`

I get the following in the log http://gw4y.com/images/dashboard.log

in my Database I see the SiloName 'Dashboard' go from Status '3' to Status '6'

but....
1) Port 8080 isn't released 
2) if I try now to go to the localhost:8080 I get this.
http://gw4y.com/images/Dashboard_Shutdown.jpg

**Comment by richorama** [comment]
thanks @PGP-Protector for reporting this issue with such detail.

I'll take a look into this when I get the chance. Hopefully this week.
