### ISSUE TITLE
Why do we use code generation?

### ISSUE THREAD

**Issue by SebastianStehle** [OrleansContrib/OrleansDashboard#211]
Do you remember why we use code generation here:

https://github.com/OrleansContrib/OrleansDashboard/blob/dc349a2e311048dd9272d64b728dfad1b9370ec6/OrleansDashboard/ServiceCollectionExtensions.cs#L21?

**Comment by richorama** [comment]
I don't know. Perhaps @matteofabbri can help?

This is the commit: https://github.com/OrleansContrib/OrleansDashboard/commit/4a386dca24722e7c137cb50329b9151dcb0e603c#diff-383701f303fce98604400e939185ec10R20

**Comment by bbougot** [comment]
> Build-time code generation only supports C#. For F#, Visual Basic, and other .NET languages, code can be generated during configuration time via the WithCodeGeneration() method described above.

More details [here](https://dotnet.github.io/orleans/Documentation/clusters_and_clients/configuration_guide/server_configuration.html).

**Comment by SebastianStehle** [comment]
I thought it only matters when I create my class library and Grains in F# or Visual Basic.

**Comment by richorama** [comment]
I guess it would be nice to have some F# tests...

**Comment by SebastianStehle** [comment]
It has been solved now.
