### ISSUE TITLE
Better support for generic grains

### ISSUE THREAD

**Issue by richorama** [OrleansContrib/OrleansDashboard#22]
i.e. 

```c#
public interface IGenericGrain<GenericType> : IGrainWithIntegerKey
{
    Task DoSomething();
}
```

shows up like 

```
MyNamespace.MyGrain`1[[MyNamespace.MyGenericType, MyAssembly, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]
```

**Comment by DixonDs** [comment]
Basically it looks like this:

![generic](https://cloud.githubusercontent.com/assets/1036478/20905685/7b6c5e64-bb4d-11e6-8b2f-aeda0d016e3b.png)
i.e. only "0, Culture=neutral, PublicKeyToken=null]]" part is shown

**Comment by richorama** [comment]
Related to https://github.com/dotnet/orleans/issues/2358

**Comment by richorama** [comment]
As of 015d114 generic grains are supported by the dashboard.
