### ISSUE TITLE
GetReminders returns an empty list while There reminders

### ISSUE THREAD

**Issue by jonimec** [OrleansContrib/OrleansDashboard#221]
Hey,

I have a problem with getReminders function in the Grain class
for some reason, the function returns an empty list while GetReminder does return a specific reminder (And the reminder is also at the RemindersTable)

Is this a known issue? am i missing something?

Thanks,

Joni

**Comment by richorama** [comment]
Hi @jonimec do the reminders show up in the dashboard?

Are you specifying a page index and size: i.e. `await client.GetReminders(1, 25);`?

Are you able to share a minimum repdroduction of the error?

**Comment by jonimec** [comment]
I'm not specifing page index and size, i'm using getReminders without any parameters
i was not able to reproduce the problem in a different project, and in the same project i have a different call to GetReminders that does work
for now we use a workaround because of schedule of the problem, so it's not an issue for me anymore, so you can close it
