### ISSUE TITLE
Dashboard doesn't work in Chrome, ERR_INCOMPLETE_CHUNKED_ENCODING error is returned

### ISSUE THREAD

**Issue by wanton7** [OrleansContrib/OrleansDashboard#222]
I'm running OrleansDashboard 2.3.1 in ASP.NET Core 3.0 preview3 with Orleans 2.3. I'm initializing dashboard with
```csharp
.UseOrleans((context, siloBuilder) =>
{
  siloBuilder.UseDashboard(options => { });
})
```

Chrome browser Version 73.0.3683.86 (Official Build) (64-bit) on Windows 10 returns `Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING` when trying to load dashboard from localhost:8080. Dashboard works in Firefox from localhost:8080. Also tried Chrome in incognito mode and same error is returned.

**Comment by wanton7** [comment]
Might be related to this https://github.com/aspnet/AspNetCore/issues/8815

**Comment by SebastianStehle** [comment]
I guess you are on your own for 3.0. I think it is not worth it to spend time for a preview version, but perhaps another contributor has time.

**Comment by wanton7** [comment]
Fixed in .NET Core 3.0 preview4.
