### ISSUE TITLE
Adding dashboard breaks automatic discovery of grain assemblys

### ISSUE THREAD

**Issue by Frank-Krick** [OrleansContrib/OrleansDashboard#225]
Adding the dashboard to the silo configuration like this `.UseDashboard(options => { options.Port = 1337; })` breaks the automatic discovery of grains. Creating any of my grains returns the following exception:
```
System.ArgumentException: Cannot find an implementation class for grain interface: Eight.Kelvin.GrainInterfaces.Grains.IDeviceGrain. Make sure the grain assembly was correctly deployed and loaded in the silo.
```

The silo runs fine without dashboard and can create instances of the grains.

**Comment by richorama** [comment]
Hi Frank, thanks for reporting this issue. Which versions of Orleans and the dashboard are you using?

Thanks,

Richard.

**Comment by Frank-Krick** [comment]
Hi Richard,

thanks for the quick response. We're using OrleansDashboard 2.3.1 and Orleans 2.3

**Comment by Frank-Krick** [comment]
I dug a bit deeper. What's happening is that the dashboard registers its assemblies with `ConfigureApplicationParts` which disables the automatic discovery of grains in the project.

I could solve the problem by adding `.ConfigureApplicationParts(parts => parts.AddFromApplicationBaseDirectory())` to the silo configuration to add my own grains back into orleans.

**Comment by richorama** [comment]
Ah ha, thanks for getting to the bottom of it. Looks like I need to update the documentation (or find a work around)

**Comment by Frank-Krick** [comment]
I create PR #226 to update the documentation for this issue.
