### ISSUE TITLE
Not easy to override GrainMethodFormatter

### ISSUE THREAD

**Issue by jsteinich** [OrleansContrib/OrleansDashboard#229]
When trying to workaround https://github.com/dotnet/orleans/issues/5627, I attempted to override the `GrainMethodFormatter` used by `GrainProfiler`. Since the default is registered [here](https://github.com/OrleansContrib/OrleansDashboard/blob/7d822ddabf6c9c9c4ab0337c5b4d01ad83cc2549/OrleansDashboard/ServiceCollectionExtensions.cs#L62) as just a singleton, I wasn't able to use any of the extension methods. I believe using `TryAddSingleton` would make it simple to register an override, but I've never tried that with a delegate.

**Comment by SebastianStehle** [comment]
PR is welcome. But you just register your implementation after the dashboard, to get it working.
