### ISSUE TITLE
It is recommended that Metrics be independent from OrleansDashboard

### ISSUE THREAD

**Issue by lfzm** [OrleansContrib/OrleansDashboard#236]
It is recommended that Metrics be independent from OrleansDashboard, create a new OrleansDashboard .Metrics Project, reduce the size of the OrleansDashboard, and separate the UI from the Metrics.

**Comment by SebastianStehle** [comment]
Who recommends that? ;)

Besides that: The Dashboard creates no new metrics, only single data points and aggregations just for the Dashboard.

**Comment by richorama** [comment]
@lfzm thank you for suggesting this. As @SebastianStehle says, that dashboard doesn't emit any metrics, it's just a simple aggregator of data that Orleans itself publishes.
