### ISSUE TITLE
Orleankka + Dashboard \n Dashboard can't see methods information

### ISSUE THREAD

**Issue by Neftedollar** [OrleansContrib/OrleansDashboard#238]
Hey!
I'm trying to use Orleankka with Dashboard.
I can see methods on the overview page
![image](https://user-images.githubusercontent.com/1009015/59768653-6b609500-92ad-11e9-932e-69c1ec1394d5.png)
```
Orleankka.IActor.ReceiveTell
Server.Grains.Scrapper+Scrapper
```
But when I click on this I can't see anything except 
```No message recorded```
![image](https://user-images.githubusercontent.com/1009015/59768796-9cd96080-92ad-11e9-8da4-3e80d93bb8a4.png)
What should I do to get all the information about this method?

**Comment by Neftedollar** [comment]
I've asked this question in the Orleankka's issues 
https://github.com/OrleansContrib/Orleankka/issues/156

**Comment by yevhen** [comment]
Which version of Dashboard? Orleankka has special [integration](https://github.com/OrleansContrib/Orleankka/blob/master/Source/Orleankka.Runtime/Cluster/DashboardIntegration.cs) with Dashboard if that wasn't broken. You should actually see the name of the messages sent to `ReceiveXXX` methods instead of method names. 

Check whether Dashboard still gets from DI the delegate with this [signature](https://github.com/OrleansContrib/Orleankka/blob/master/Source/Orleankka.Runtime/Cluster/ClusterOptions.cs#L113)

**Comment by Neftedollar** [comment]
> Which version of Dashboard? 
<PackageReference Include="OrleansDashboard" Version="2.3.4" />

@yevhen I forget to mention that I use F# version of Orleankka. Is it usefull?

**Comment by Neftedollar** [comment]
@yevhen 
is this dependency
` services.TryAddSingleton<Func<MethodInfo, InvokeMethodRequest, IGrain, string>>(DashboardIntegration.Format);
` is for delegate `new GrainProfilerFilter.GrainMethodFormatterDelegate` ?

**Comment by Neftedollar** [comment]
> Check whether Dashboard still gets from DI the delegate with this [signature  ](https://github.com/OrleansContrib/Orleankka/blob/master/Source/Orleankka.Runtime/Cluster/ClusterOptions.cs#L113)

As I understand here is it:
![image](https://user-images.githubusercontent.com/1009015/59774837-d1064e80-92b8-11e9-9bcb-5c8b17f618db.png)
And cropped
![image](https://user-images.githubusercontent.com/1009015/59774986-0d39af00-92b9-11e9-9196-0797ccb25879.png)

**Comment by richorama** [comment]
I believe that @SebastianStehle has refactored the profiler, so rather then providing a function to format the method name, you can now provide a custom profiler instead.

I think we should re-introduce the method name formatter to maintain backwards compatibility.

**Comment by SebastianStehle** [comment]
The delegate is still there: https://github.com/OrleansContrib/OrleansDashboard/blob/master/OrleansDashboard/Metrics/GrainProfilerFilter.cs

But `Func<MethodInfo, InvokeMethodRequest, IGrain, string>` is not the same type as `GrainProfilerFilter.GrainMethodFormatterDelegate`

**Comment by Neftedollar** [comment]
@richorama @SebastianStehle
Where can I find any example of custom provider

**Comment by Neftedollar** [comment]
@yevhen maybe you have some knowledge or ideas?

**Comment by yevhen** [comment]
@SebastianStehle can you switch back to `Func<MethodInfo, InvokeMethodRequest, IGrain, string>` since I can't take hard dependency on Orleans Dashboard?

**Comment by Neftedollar** [comment]
@yevhen 
as a fast workaround:
Can you make `Formatter` public? The user will glue you `formatter` with GrainMethodFormatterDelegate by himself

**Comment by SebastianStehle** [comment]
@yevhen No, but I can support both ;)

**Comment by SebastianStehle** [comment]
I just realized that `InvokeMethodRequest` is not used anymore. Can we chjangei t to `Func<IIncomingGrainCallContext, string>`?

**Comment by SebastianStehle** [comment]
I have pushed an update.

**Comment by Neftedollar** [comment]
@SebastianStehle @richorama @yevhen  Thank you!
