### ISSUE TITLE
ASP.NET Core 3.0

### ISSUE THREAD

**Issue by SebastianStehle** [OrleansContrib/OrleansDashboard#259]
If I understand it correctly. ASP.NET Core 3.0 does not .NET Framework anymore and the class libraries have to be written in `netcoreapp3.0` as well.

if this is the case, we should think about how to split up the code, because some classes like NoProfilingAttribute` should also be accessible from NetStandard

I would suggest 2 or 3 libraries

* OrleansDashboard.Core: Everything that is not related to clients and ASP.NET.
* OrleansDashboard.Runtime: ASP.NET Core stuff.

We can also move the implementation in its own library, but I am not sure why.

Root namespace should be always OrleansDashboard

In my opinion the client assembly is not needed and a little bit confusing anyway.

What do you think?

**Comment by richorama** [comment]
I agree we should upgrade to 3.0.

I'm not sure in the value of supporting the full .NET framework any more, do people still use it?

@matteofabbri what are your thoughts on the client?

**Comment by SebastianStehle** [comment]
As Orleans still targets NetStandard2.0, we should do it as well...

**Comment by SebastianStehle** [comment]
What shall we do now?

**Comment by richorama** [comment]
I’m in support. Go for it.

**Comment by SebastianStehle** [comment]
Okay. Btw: The dashboard is already compatible with ASP.NET Core 3.0. It seems that the features we use are binary compatible already. But anyway, we should migrate it. Will do it this week.
