### ISSUE TITLE
support custom user ordering of grain method invocation charts

### ISSUE THREAD

**Issue by danvanderboom** [OrleansContrib/OrleansDashboard#26]
The order grain methods appear in the dashboard won't match the expectations and needs of developers and IT admins unless they can change it and have those changes tracked by Orleans Dashboard. Some grain methods occur in pairs or larger groups, and some calls or groups of calls are related to different stages of custom business processes. Being able to put those calls in an order that represents the understanding of the organization monitoring the data has value.

Let the user move grain method charts up or down on the page. Save that sort order so all new dashboard sessions assume the new sort order.

**Comment by richorama** [comment]
closed by #174
