### ISSUE TITLE
OrleansDashboard.Core 3.0.4 is not on nuget

### ISSUE THREAD

**Issue by rmja** [OrleansContrib/OrleansDashboard#273]
OrleansDashboard 3.0.4 [depends on OrleansDashboard.Core 3.0.4](https://www.nuget.org/packages/OrleansDashboard/3.0.4) but [it does not exist on nuget](https://www.nuget.org/packages/OrleansDashboard/3.0.4).

**Comment by SebastianStehle** [comment]
Thx, I guess there is a bug in the action, will try to fix it.

**Comment by SebastianStehle** [comment]
Solved

**Comment by richorama** [comment]
Thanks for sorting @SebastianStehle

**Comment by SebastianStehle** [comment]
I am an egoist, I wanted to use it myself. ;)
