### ISSUE TITLE
Switch to 'Create React App' / typescript

### ISSUE THREAD

**Issue by richorama** [OrleansContrib/OrleansDashboard#278]
Wondering about switching to [CRA](https://github.com/facebook/create-react-app) to simplify the UI build, perhaps switching to TS at the same time?

**Comment by SebastianStehle** [comment]
Only when you also update the server to serve the scripts from the dev server in dev mode.

**Comment by richorama** [comment]
I was thinking of using webpack's web server during development, and using CORS to call the dashboard.

**Comment by richorama** [comment]
WIP
