### ISSUE TITLE
Log spam from OrleansDashboard.Metrics.GrainProfiler

### ISSUE THREAD

**Issue by justmara** [OrleansContrib/OrleansDashboard#279]
After updating to 3.0.7 our logging subsystem exploded with messages from `OrleansDashboard.Metrics.GrainProfiler` on `Information` level. Those messages contains nothing but grain type name. Looks like the source is [this string](https://github.com/OrleansContrib/OrleansDashboard/blob/445aa125aa76d30da501ab83d244c3dd26e73e08/OrleansDashboard.Core/Metrics/GrainProfiler.cs#L89).
Why it is set on Information level? Why it is enabled by default?

**Comment by SebastianStehle** [comment]
Can you provide a PR? you can also increment version number in this PR.

**Comment by richorama** [comment]
Sorry, my bad. Fixed in 3.0.8
