### ISSUE TITLE
OrleansDashboard not support  .NETStandard 2.0

### ISSUE THREAD

**Issue by EranOfer** [OrleansContrib/OrleansDashboard#280]
Hi,
I want to consume OrleansDashboard from  4.7.2.
the problem is the nuspc only target framework NETCoreApp3.0.

![image](https://user-images.githubusercontent.com/13414515/71966940-27ae8800-320b-11ea-987d-7b2a27682c77.png)

# Orleans 3 require .NETStandard 2.0

![image](https://user-images.githubusercontent.com/13414515/71967034-54fb3600-320b-11ea-9ffc-9cc37426cf67.png)

**Comment by SebastianStehle** [comment]
Orleans Dashboard uses ASP.NET Core 3.0 and it only supports .NET Core right now. If you have a solution: You are welcome :)

**Comment by EranOfer** [comment]
thanks 👍
