### ISSUE TITLE
[WIP] Dashboard collection reduces unrelated references

### ISSUE THREAD

**Issue by lfzm** [OrleansContrib/OrleansDashboard#282]
When Dashboard and Dashboard collection are used separately, many unrelated component references will be added. E.g. `AspNetCore.APP`

You should only need `SiloHostBuilder.UseDashboardCollect ()` when collecting

**Comment by shersh** [comment]
Hello! 
Any new about this issue?

**Comment by SebastianStehle** [comment]
It has no priority.
