### ISSUE TITLE
Not working with AspNetCoreCohosting example

### ISSUE THREAD

**Issue by hotyes** [OrleansContrib/OrleansDashboard#286]
I am trying to add dashboard with AspNetCoreCohosting example (https://github.com/dotnet/orleans/tree/master/Samples/3.0/AspNetCoreCohosting), when I try to call my grain it will throw error `Cannot find an implementation class for grain interface: IMyCustomGrain. Make sure the grain assembly was correctly deployed and loaded in the silo.`

I am using default config for dashboard. orleans version 3.1.2

**Comment by bartziengs** [comment]
I faced something similar. If you look in the readme it says:
"Please note, the dashboard registers its services and grains using ConfigureApplicationParts which disables the automatic discovery of grains in Orleans. To enable automatic discovery of the grains of the original project, change the configuration to:"

Try adding the applicationparts (either from from basedirectory or load an assembly of the interfaces with:

```
                .ConfigureApplicationParts(parts =>
                {
                    parts.AddApplicationPart(typeof(IMyCustomGrain).Assembly).WithReferences();
                })
```
