### ISSUE TITLE
[Question] performance counters in a silo hosted in a kubernetes cluster

### ISSUE THREAD

**Issue by GersonDias** [OrleansContrib/OrleansDashboard#289]
when I start my silo in a kubernetes cluster I receive the warning:

```Error initializing CPU & Memory perf counters - you need to repair Windows perf counter config on this machine with 'lodctr /r' command```

there are a way to have those CPU/RAM counters when we running the silo in a Windows container?

**Comment by richorama** [comment]
I'm afraid I don't know the answer to this one. It sounds like a problem with the environment rather than the dashboard itself?

**Comment by GersonDias** [comment]
yes, not related to the dashboard itself, but hoping someone have some guidance on how to properly run those counters in a kubernetes cluster running windows containers...
