### ISSUE TITLE
Custom grain names

### ISSUE THREAD

**Issue by gparissis** [OrleansContrib/OrleansDashboard#291]
Just a thought now that i have created my application and i see many grains loaded.
Is it possible to have a custom grain name reported on the dashboard? For example i see IVendorGrain, but i would prefer if i had the option to change the name to something else not related with the code semantics, like "Vendors"
The same could be applied when i click on a grain to see the functions performance. So instead of something like UpdateIfGenerated to something more readable "Updates for generated vendors".
Does it make sense to have this capability?

**Comment by richorama** [comment]
Yes, I believe that if you register an implementation of `GrainMethodFormatterDelegate` then you can customise the method names.

**Comment by SebastianStehle** [comment]
No, thats only for the method names. So far there is nothing.

**Comment by gparissis** [comment]
I have searched for GrainMethodFormatterDelegate but i wasn't able to find any example or how-to. Can you please provide me with a link or can you give me a very basic example?

Thank you.
