### ISSUE TITLE
Using Dashboard in Docker Container

### ISSUE THREAD

**Issue by sjbthfc2** [OrleansContrib/OrleansDashboard#292]
Hi,

I am trying to use the dashboard in a silo running in a Docker Container as part of an ASP .NET Core 3.1 Web API process. Using the Docker features in Visual Studio, I have a Docker file which exposes port 8080. When I try and access the dashboard through http://localhost:8080 I just get connection refused.

It runs fine if I run it outside of the Container. Is there anything else I need to do to expose the dashboard? I use * for the host option and have left the default port as 8080.

Many thanks

**Comment by richorama** [comment]
Hi @sjbthfc2 , thanks for your bug report.

I assume you're mapping the ports through from the container correctly?

I don't know of any particular setting you need to set for running inside a container I'm afraid, and it's not a configuration that I test.

**Comment by sjbthfc2** [comment]
Hi,

It is working now, it was my mistake. I see now in Visual Studio that exposed ports get mapped to ports selected by VS when you run the project in a container. I am going through the correct port now from localhost as mapped by VS.

Thanks

![image](https://user-images.githubusercontent.com/3796984/87051224-35af8680-c1f7-11ea-8245-2f4c4292488c.png)

**Comment by richorama** [comment]
Great, glad you got it working! 😃
