### ISSUE TITLE
Add https and make it be co-hosted with ASP.NET

### ISSUE THREAD

**Issue by alexanderfedinatnasa** [OrleansContrib/OrleansDashboard#302]
Subj.

**Comment by richorama** [comment]
Hi @alexanderfedinatnasa,

The dashboard can be hosted by asp.net core, and is added via middleware. This should allow you to configure HTTPS for it.

You can turn off the self hosting when configuring the dashboard:

```cs
new SiloHostBuilder()
    .UseDashboard(options =>
    {
        options.HostSelf = false;
    })
```

Please see this test application as a complete example:

https://github.com/OrleansContrib/OrleansDashboard/blob/master/Tests/TestHosts/TestHostSeparate/Program.cs
