### ISSUE TITLE
Deployment on AKS

### ISSUE THREAD

**Issue by keshavraja** [OrleansContrib/OrleansDashboard#307]
I am trying to deploy the dashboard on AKS but having hard luck. Anyone who has deployed on AKS.

**Comment by SebastianStehle** [comment]
No, but on kubernetes on GCE. What is the issue?

**Comment by keshavraja** [comment]
I am getting 502 gateway error, I am using the following code
 siloBuilder.UseDashboard(options =>
                        {
                            options.Username = XXXXX;
                            options.Password = XXXX;                            
                            options.Host = "*";
                            options.Port = 80;                            
                            options.HostSelf = true;
                            options.CounterUpdateIntervalMs = 10000;
                            options.HideTrace = true;
                        });
In terraform script, I have added a service exposing 80 ports.

**Comment by richorama** [comment]
@keshavraja try switching `HostSelf` to 'false'. That flag is used to indicate that you want to add the dashboard to your ASP.NET middleware, and not have it start itself as a web server.

**Comment by keshavraja** [comment]
Yes, I have tried that and getting the same error. I am attaching my ingress service screenshot, the IP is properly bound and the service is also running. But when I am pulling the dashboard I am getting a 502 error.
![image](https://user-images.githubusercontent.com/12935521/123635798-b4069d80-d839-11eb-9109-1d18d68f0a5a.png)

**Comment by SebastianStehle** [comment]
Can you run it locally? When it works, then it is a kubernetes issue and we cannot provide support for your special deployment scenario. The kubernetes is just a normal asp.net core / kestrel setup.

**Comment by keshavraja** [comment]
Thank you @SebastianStehle, I will try setting up Kubernetes locally and see it is working.

**Comment by SebastianStehle** [comment]
I within with the debugger and kestrel. Perhaps you have forgotten a port mapping or something like this. If  it works with Visual Studio it has something to do with your setup

**Comment by Expecho** [comment]
@keshavraja I do have it running, but not as a standalone pod. The dashboard is cohosted with an asp.net web project.

**Comment by keshavraja** [comment]
I got this running. There was an ingress routing issue at my end. Thank you !!
