### ISSUE TITLE
Dashboard behind firewall

### ISSUE THREAD

**Issue by SebastianStehle** [OrleansContrib/OrleansDashboard#308]
Hi,

I am using Orleans Dashboard for Squidex, a headless CMS, and I have a request from a user, who runs Squidex in a corporate environment with strict firewalls. I have seen it before, that CDNs are often blocked.

If I would provide a PR to host the files locally, how would you prefer it?

1. Just integrate the files as resources into the assembly and load from there?
2. Option 1, but which a option to turn it on or off?
3. Integrate the files into a separate assembly, so that you do not have the extra 5 MB in your app, if you don't need it?

**Comment by richorama** [comment]
Hey Sebastian!

Option 3 is my preference. If we could have a separate nuget package for the offline resources if needed it would be the best of both worlds. Happy to help out on this if needed.

**Comment by SebastianStehle** [comment]
I think it is relatively straight forward. I am going to introduce an interface for that to call in the middleware. The default implementation is just going to do a redirect to a CDN then and then another implementation which loads the resources from embedded resources.
