### ISSUE TITLE
Log stream doesn't work when using serilog

### ISSUE THREAD

**Issue by ScarletKuro** [OrleansContrib/OrleansDashboard#314]
I added serilog to my project and noticed that log stream doesn't work anymore. Just getting "connecting..." 
When I removed serilog for testing purpose the log stream was working again.

If repro repository will be necessary let met know.

**Comment by richorama** [comment]
Thanks for reporting this, I will investigate.

**Comment by ScarletKuro** [comment]
Found the solution, idk why I thought about it only now because the problem is in the loggedprovider and it should be obvious, but yea.
Looking at Serilog api we can see
```    
public static IHostBuilder UseSerilog(
      this IHostBuilder builder,
      Action<HostBuilderContext, IServiceProvider, LoggerConfiguration> configureLogger,
      bool preserveStaticLogger = false,
      bool writeToProviders = false)
```
Default `writeToProviders` is `false`, setting it `.UseSerilog(..., false, true)` fixes the problem.
@richorama I will close the issue, but I think this can be added in documentation.
