### ISSUE TITLE
Kubernetes perf counter

### ISSUE THREAD

**Issue by KSemenenko** [OrleansContrib/OrleansDashboard#322]
Hi all!
Does anyone know a way to get performance information in Kubernetes?
<img width="1538" alt="Screenshot 2021-08-24 at 15 27 46" src="https://user-images.githubusercontent.com/4385716/130624971-f4d16a50-787e-4566-b70b-70e3b27b8d88.png">

**Comment by richorama** [comment]
Hey @KSemenenko,

Have you tried adding the linux telemetry consumer?

> Since version 2.3, Orleans includes an implementation of IHostEnvironmentStatistics for Linux in Microsoft.Orleans.OrleansTelemetryConsumers.Linux. To enable CPU and Memory metrics, install the NuGet package and add the implementation to the silo using siloBuilder.UseLinuxEnvironmentStatistics().

**Comment by KSemenenko** [comment]
I have this two

```
<PackageReference Include="Microsoft.Orleans.OrleansTelemetryConsumers.Counters" Version="3.4.3"/>
 <PackageReference Include="Microsoft.Orleans.OrleansTelemetryConsumers.Linux" Version="3.4.3"/>
```

and this one
```
siloBuilder.UsePerfCounterEnvironmentStatistics();
```

so, I add this line  siloBuilder.UseLinuxEnvironmentStatistics() and it works!!

Thanks a lot!!
