### ISSUE TITLE
When publishing to docker, there is an error in the picture

### ISSUE THREAD

**Issue by NigelYu** [OrleansContrib/OrleansDashboard#330]
![image](https://user-images.githubusercontent.com/4321593/142585047-7968f8de-ae56-4783-9049-a2233df6a5f6.png)

After I removed the Dashboard, everything worked fine；

![image](https://user-images.githubusercontent.com/4321593/142586514-f277a863-bfc5-417b-a701-0cf51f34a86e.png)

**Comment by SebastianStehle** [comment]
Are you running it with .NET6.0?

**Comment by NigelYu** [comment]
used .Net 5 @SebastianStehle

**Comment by NigelYu** [comment]
I use VisualStudio to generate a mirror image, and then deploy to docker, there will be such a problem

**Comment by NigelYu** [comment]
独立部署的silohost app  会有这个问题，集成在WEBAPI项目中就一切正常

The independently deployed silohost app will have this problem, and everything is normal when integrated in the WEBAPI projec
