### ISSUE TITLE
Multitarget dotnet 3.1 and net5/6? 

### ISSUE THREAD

**Issue by archonandrewhunt** [OrleansContrib/OrleansDashboard#332]
Bit of a long shot, but has there been any thoughts about multi-targeting to still support those projects still on dotnet 3.1? 3.1 isn't EOL until Dec 3, 2022.

**Comment by richorama** [comment]
I don't think I have the capacity to support .NET 3.x unfortunately. Feel free to fork this repo!

**Comment by archonandrewhunt** [comment]
Thanks, we ended up moving all our stuff to net6 recently so became a non-issue. Understand the reasoning either way.
