### ISSUE TITLE
Should I UseDashboard() for all hosts in a cluster?

### ISSUE THREAD

**Issue by AntonPetrov83** [OrleansContrib/OrleansDashboard#333]
Hi!

This is not very clear from the README - should I UseDashboard() for all processes in the cluster or only for that which will host the dashboard?

**Comment by richorama** [comment]
Short answer - yes, install the dashboard on every silo in the cluster.

Long answer - the dashboard will still partially function if only installed on one or more silos, but you'll miss out on the grain profiling and log streaming for silos that are not monitored.

**Comment by richorama** [comment]
I have added a line to the readme to clarify that it should be installed on every silo. Thanks for pointing this out :¬)
