### ISSUE TITLE
Ability to turn metrics capture on/off

### ISSUE THREAD

**Issue by richorama** [OrleansContrib/OrleansDashboard#338]

**Comment by richorama** [comment]
..although I would prefer to fix the perf issue, than to navigate around it.

**Comment by ElanHasson** [comment]
It seems viewing the dashboard increases CPU usage by 20-30%

<img width="999" alt="image" src="https://user-images.githubusercontent.com/234704/153754931-55fedd66-8eba-41b1-b433-122200085e06.png">

**Comment by richorama** [comment]
v4.0 will only capture metrics while you're observing.
