### ISSUE TITLE
Track OnActivateAsync on the grain view

### ISSUE THREAD

**Issue by DixonDs** [OrleansContrib/OrleansDashboard#34]
Currently methods stats shown on the grain view are not including `OnActivateAsync` which itself could take some time. Is there an easy way to add it and probably `OnDeactivateAsync`?

**Comment by richorama** [comment]
I don't believe interceptors are called explicitly for OnActivateAsync, so I can't collect this method. I assume it would contribute to the time taken in the first call to the grain.

Is it worth raising an issue on Orleans to see if this is possible?

**Comment by DixonDs** [comment]
I think if it is indeed not caught by interceptors (I am not yet familiar with them), probably it would be a good option to have it, so yes

**Comment by richorama** [comment]
there's already an issue for it here: https://github.com/dotnet/orleans/issues/1871

**Comment by richorama** [comment]
I'm parking this issue, as there's currently no way of implementing it.
