### ISSUE TITLE
Orleans v4 preview has been released, will need to upgrade

### ISSUE THREAD

**Issue by ElanHasson** [OrleansContrib/OrleansDashboard#346]
Would it be possible to have a branch and nugets for Orleans v4 ?

**Comment by SebastianStehle** [comment]
No, it is not that easy. For example we have to annotate our POCOs and check other incompatibilities.

**Comment by ElanHasson** [comment]
Oh yes, I know :)

**Comment by SebastianStehle** [comment]
You could work on that and provide a PR. From my side It would be good enough to wait for the final release. It can be very annoying to go through all the betas and RCs.

**Comment by ElanHasson** [comment]
Primary differences in the Hello World example is around silohost and siloclient. I ran into trouble with cluster membership. My saga is detailed on the Orleans discord

**Comment by richorama** [comment]
#348
