### ISSUE TITLE
What is this line?

### ISSUE THREAD

**Issue by SebastianStehle** [OrleansContrib/OrleansDashboard#349]
https://github.com/OrleansContrib/OrleansDashboard/blame/master/OrleansDashboard/Implementation/Grains/DashboardGrain.cs#L79

@richorama Do you remember the reason of this comment? Probably not ;)

**Comment by richorama** [comment]
No, I don't remember what I meant by that comment (apologies, it wasn't a very helpfile thing to write).

**Comment by SebastianStehle** [comment]
Okay, thanks.
