### ISSUE TITLE
Invalid total request/second values

### ISSUE THREAD

**Issue by DixonDs** [OrleansContrib/OrleansDashboard#35]
It looks like the total requests/second value is the average from individual, per-silo requests/second values. Correct me please if I am wrong, but if one silo gives X requests/second and the other one - Y requests/second, doesn't it mean the totally two silos serve X+Y requests per second?

![rps](https://cloud.githubusercontent.com/assets/1036478/22332387/5bd0adee-e3d9-11e6-9c4a-0fbee45afe00.png)

**Comment by richorama** [comment]
Yes, I think you're right. It's currently the average per silo, but it should be the sum. 

I'll fix it.

**Comment by richorama** [comment]
I have modified this slightly so it says `req/sec/silo`. This won't be that easy to fix because of the way the stats are collected..

**Comment by DixonDs** [comment]
It is good as a quick fix, but I think in long-term, the total requests/second value seems to be more informative.

**Comment by richorama** [comment]
@DixonDs agreed

**Comment by richorama** [comment]
Fixed in version 1.4.6

**Comment by DixonDs** [comment]
@richorama I think there is the same issue on the general grain overview page ("/#/grains"). Shall I open a separate issue?

**Comment by richorama** [comment]
@DixonDs thanks for reporting, I'll just reopen this one.
