### ISSUE TITLE
Collect only data while the dashboard is open?

### ISSUE THREAD

**Issue by SebastianStehle** [OrleansContrib/OrleansDashboard#353]
We made a lot of attempts to keep the performance up but the fastest approach would be not to collect data at all, when nobody is actually interested in it.

We could use a grain to track whether someone is actually interested in the data and then broadcast this to all silos to turn tracking on or off.

Of couse you would have to wait 100 seconds to get some valuable data, but it would be the fastest approach.

**Comment by richorama** [comment]
yes, I wondered about this as well. My thought was to have some different modes set by config:

1. Collect data all the time
1. Collect data when switched on/off by a button on the dashboard
1. Collect data only when the dashboard is open.

**Comment by SebastianStehle** [comment]
I think for option 2. we would have to store the state somewhere, which I would avoid.

**Comment by richorama** [comment]
good point

**Comment by SebastianStehle** [comment]
The question is: How to implement that:

1. We can easily track the active status in the dashboard grain. We just need a flag that is set to true for each request and automatically set to false after some time without activity by using a timer.

2. We need to track this status on each grain. We can use the silo grain for that, but we have to ensure that it lives once on each silo. The easiest approach is to never activate it from outside. Therefore I would say that the silo grain should be activated in the silo itself with a random ID and then it registers itself to the dashboard grain. To make it resilient when the dashboard grain dies, we need a periodic ping from the 

We can then send the active flag to all registered silo grains when the status changes and the grain is calling a singleton service which holds this flag as well.

3. The filters also inject this singleton service and only collects data when the flag is true.

What do you think about this approach?

**Comment by richorama** [comment]
I wonder if it's easier to just turn all the dashboard data capturing on/off rather than just enabling individual grains/silos, as some metrics are aggregated to give cluster-wide numbers.

**Comment by SebastianStehle** [comment]
I would not turn off individual silos, but we have to sync this value across all silos. I mean we could also query the dashboard grain and query that, but it would have a long delay and create unnecessary calls.
