### ISSUE TITLE
Show silo name besides silo address

### ISSUE THREAD

**Issue by wangjia184** [OrleansContrib/OrleansDashboard#356]
Currently the amazing dashboard presents silo addresses in table. To know the silo name(POD name when running in K8S), one needs to check in the silo's details page. Better to have silo name aside in the same table so it is more meaningful. 

![image](https://user-images.githubusercontent.com/2765840/163662793-8821f5be-6411-4676-8621-d5b7eb9033dc.png)

**Comment by wangjia184** [comment]
PR is here: https://github.com/OrleansContrib/OrleansDashboard/pull/357

**Comment by richorama** [comment]
resolved by #357
