### ISSUE TITLE
Label for `Orleans.Providers.MemoryStreamQueueGrain`

### ISSUE THREAD

**Issue by DixonDs** [OrleansContrib/OrleansDashboard#36]
Currently grains from namespaces starting from `System.Runtime` as marked as "System grain". I guess we either include also `Orleans.Providers.*` grains to "system grains", or have a separate label for them.

**Comment by DixonDs** [comment]
I guess similarly about `Orleans.Streams.PubSubRendezvousGrain`

**Comment by richorama** [comment]
@DixonDs thanks for reporting this. I have changed the logic to any grain starting with `Orleans.` is marked as a system grain.
