### ISSUE TITLE
Dependency on Microsoft.Orleans.Runtime.Abstraction breaks on Orleans 4.0 preview 2

### ISSUE THREAD

**Issue by tanordheim** [OrleansContrib/OrleansDashboard#369]
The `OrleansDashboard.Core` nuget package has a dependency on `Microsoft.Orleans.Runtime.Abstractions ≥ 3.6.0` which is causing me some issues when installing OrleansDashboard in a project that depends on Orleans 4.0 preview 2:

```
SiloBuilder.cs(8, 36): [CS0433] The type 'ISiloBuilder' exists in both 'Orleans.Runtime.Abstractions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' and 'Orleans.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'
```

**Comment by SebastianStehle** [comment]
There should be a pre-release package for beta1, feel free to open a PR for beta2 ;)
