### ISSUE TITLE
Example hosting with Silo in AppService?

### ISSUE THREAD

**Issue by jsmithtx** [OrleansContrib/OrleansDashboard#372]
I have tried to get this working both locally and on an AppService with an Orleans cluster that is hosted on the same App Service and nothing works. I attempted the basic "UseDashboard" instructions and browsing to 8080 doesn't exist. Self hosting fails as it can't find /dashboard. Adding the path of /dashboard causes missing registration issue. If I get those registered it still throws a 404.

```
.ConfigureApplicationParts(p => p.AddFromApplicationBaseDirectory())
.UseDashboard(opts => opts.HostSelf= false)
```

Is there a comprehensive document that shows how to get this working? I am running an ASP.NET Core Web API project (netcore6.0). The Silo is in the same project as the dashboard. Thanks!

**Comment by richorama** [comment]
This sample works for me:
```cs
using Microsoft.AspNetCore.Http.Extensions;
using Orleans;
using Orleans.Hosting;

var builder = WebApplication.CreateBuilder();

builder.Host.UseOrleans(siloBuilder =>
{
  siloBuilder.UseLocalhostClustering();
  siloBuilder.UseDashboard(x => x.HostSelf = true);
});

var app = builder.Build();

app.Map("/dashboard", x => x.UseOrleansDashboard());
```

Are you following the same broad steps?

**Comment by jsmithtx** [comment]
This worked. Must have tried everything BUT that! Thanks

**Comment by richorama** [comment]
I will include this in the docs...
