### ISSUE TITLE
Orleans does not always report CPU and Memory usage

### ISSUE THREAD

**Issue by richorama** [OrleansContrib/OrleansDashboard#38]
![blob](https://cloud.githubusercontent.com/assets/353138/24355043/54c33908-12ec-11e7-8301-e52338193a17.png)

**Comment by SebastianStehle** [comment]
Testing it for 2.0, but there is a bug: https://github.com/dotnet/orleans/issues/4129

**Comment by SebastianStehle** [comment]
Solved by: https://github.com/OrleansContrib/OrleansDashboard/pull/113
