### ISSUE TITLE
"unknown comma" on generic Grain

### ISSUE THREAD

**Issue by lwansbrough** [OrleansContrib/OrleansDashboard#39]
I have a grain that's defined like `HelloGrain : Grain, IHelloGrain<T, U>` and I receive a console log message: "unknown comma" when this type of Grain is parsed by the `TypeFormatter`. For your reference, this type of generic functionality has been possible in Orleans since 1.4.0.

**Comment by richorama** [comment]
Good find. I'll fix this next week. I'm away for a few days.

**Comment by richorama** [comment]
Fixed by release 1.4.3

**Comment by lwansbrough** [comment]
Awesome, thanks!
