### ISSUE TITLE
Constantly logged Invalid Message: OneWay

### ISSUE THREAD

**Issue by gufigueiredo** [OrleansContrib/OrleansDashboard#394]
When I call any grain, the dashboard starts to output the following error message, once per second:

`[17:00:34 ERR] Invalid message: OneWay [S10.246.34.62:11111:40334262 sys.client/hosted-10.246.34.62:11111@40334262]->[S10.246.34.62:11111:40334262 sys.svc.user.95B6CAE6/10.246.34.62:11111@40334262] OrleansDashboard.ISiloGrainServiceOrleansDashboard.ISiloGrainService.ReportCounters(Orleans.Concurrency.Immutable'1[OrleansDashboard.Model.StatCounter[]]) #1614
`

Orleans Version: 7.1.1
Dashboard Version: 7.2.0

**Comment by ReubenBond** [comment]
Thank you for reporting this. It was recently fixed via https://github.com/dotnet/orleans/pull/8364. The fix will be available in the next release.

**Comment by gufigueiredo** [comment]
@ReubenBond in the next release of Orleans, right?
