### ISSUE TITLE
Support for Silo Cluster?

### ISSUE THREAD

**Issue by Pravin4Derivco** [OrleansContrib/OrleansDashboard#4]
Hi,

Thanks for this very handy tool.
I have tried this with a standalone silo, where this looks perfectly fine; but I would like to know if this code also works with Cluster of Silos. Thanks.

Regards,

Pravin

**Comment by richorama** [comment]
It should work just fine. Let me know if you're having any trouble.

**Comment by Pravin4Derivco** [comment]
Thanks for your reply. Right now I am working on Silo Clustering; and struggling badly with it :-). And once that is done, I will definitely write you if I have any trouble with Dashboard. Thanks again.

**Comment by richorama** [comment]
No problem. BTW, there is a chat room where you can ask questions to get you started: https://gitter.im/dotnet/orleans

**Comment by Pravin4Derivco** [comment]
Thanks Rich.
