### ISSUE TITLE
Provide streaming log output per silo

### ISSUE THREAD

**Issue by rikbosch** [OrleansContrib/OrleansDashboard#40]
First of all, nice work on the dashboard!

I think viewing the logs directly in the dashboard is a great approvement.
Maybe stream the logs output through a websocket (like azure streaming log in webapps https://github.com/projectkudu/kudu/wiki/Diagnostic-Log-Stream )

**Comment by richorama** [comment]
great idea!

**Comment by richorama** [comment]
implemented in version 1.4.5
