### ISSUE TITLE
Do not load every referenced type when collecting grain types

### ISSUE THREAD

**Issue by alrz** [OrleansContrib/OrleansDashboard#428]
this is the method that currently do this:
 https://github.com/OrleansContrib/OrleansDashboard/blob/59ba91be250993bde4a14a0f98fc845301657ed6/OrleansDashboard/Implementation/Helpers/GrainStateHelper.cs#L12-L20

AFAIK orleans generator already collects all relevant types, can this utilize it instead of reflection?

**Comment by richorama** [comment]
feel free to raise a PR :¬)
