### ISSUE TITLE
Silo will not properly shutdown if viewing logstream

### ISSUE THREAD

**Issue by JasonGalea** [OrleansContrib/OrleansDashboard#43]
**BACKGROUND**

Using Orleans.Dashboard 1.4.7
Using Orleans 1.4.1

**PROBLEM**

The silo will not stop when viewing the log stream page

**IMPACT**

In an automated CI/CD pipeline environment, releases can fail if someone happens to be viewing the log stream.  This is unacceptable.

**STEPS TO REPRODUCE**
1. start silo
2. navigate to the dashboard, any page except 'Log Stream'
3. stop silo
 ==> observe the silo cleanly stops (as per log 1 below)
4. re-start silo
5. navigate to the dashboard, to 'Log Stream' page
6. stop silo
 ==> observe the silo does not stop (as per log 2 below)

**CONTEXT**
Shutting down the silo is done by the following code.
Incidentally, the exception does not bubble up from ShutdownOrleansSilo().
In fact, the call to ShutdownOrleansSilo() never even returns
        
>        public void Stop()
>        {
>            this.logger.Info($"Stopping Orleans Silo...");
>            try
>            {
>                if (this.siloHost != null)
>                {
>                    this.siloHost.ShutdownOrleansSilo();
>                    this.siloHost.Dispose();
>                    this.siloHost = null;
>                    this.logger.Info($"Orleans silo '{this.siloHost.Name}' shutdown.");
>                }
>
>                this.logger.Info("Orleans Silo Stopped");
>            }
>            catch (Exception exc)
>            {
>                this.logger.Fatal("Orleans Host Stop {@Error}: ", exc);
>
>                if (this.siloHost != null)
>                {
>                    this.siloHost.Dispose();
>                    this.siloHost = null;
>                }
>            }
>        }

**LOGS**
> ------------------------------------------------------------------------
> log 1 - when NOT viewing the 'Log Stream' page --
> ------------------------------------------------------------------------
> [2017-04-20 22:52:23.040 GMT     7	INFO   	100000	ManagementGrain	10.88.42.55:22222]	GetDetailedHosts onlyActive=True	
> [2017-04-20 22:52:23.065 GMT    10	INFO   	100000	SiloControl	10.88.42.55:22222]	GetSimpleGrainStatistics	
> [2017-04-20 22:52:23.105 GMT     5	INFO   	100294	SystemStatus	10.88.42.55:22222]	SystemStatus=Stopping	
> [2017-04-20 22:52:23.107 GMT     5	INFO   	100414	Silo	10.88.42.55:22222]	Silo starting to Stop()	
> [2017-04-20 22:52:23.110 GMT     6	INFO   	100607	MembershipOracle	10.88.42.55:22222]	-Stop	
> [2017-04-20 22:52:23.122 GMT     9	INFO   	102927	Orleans.Runtime.ReminderService.LocalReminderService	10.88.42.55:22222]	Stopping Orleans.Runtime.ReminderService.LocalReminderService grain service	
> [2017-04-20 22:52:23.151 GMT     5	INFO   	100413	Silo	10.88.42.55:22222]	Silo is Stopped()	
> [2017-04-20 22:52:23.163 GMT    10	INFO   	100609	MembershipOracle	10.88.42.55:22222]	-KillMyself	
> [2017-04-20 22:52:23.174 GMT     6	INFO   	100328	Runtime.Scheduler.WorkerPoolThread/0	10.88.42.55:22222]	Stopping AsyncAgent Runtime.Scheduler.WorkerPoolThread/0 that runs on managed thread 6	
> [2017-04-20 22:52:23.174 GMT     8	INFO   	100328	Runtime.Scheduler.WorkerPoolThread/2	10.88.42.55:22222]	Stopping AsyncAgent Runtime.Scheduler.WorkerPoolThread/2 that runs on managed thread 8	
> [2017-04-20 22:52:23.174 GMT     7	INFO   	100328	Runtime.Scheduler.WorkerPoolThread/1	10.88.42.55:22222]	Stopping AsyncAgent Runtime.Scheduler.WorkerPoolThread/1 that runs on managed thread 7	
> [2017-04-20 22:52:23.174 GMT    10	INFO   	100328	Runtime.Scheduler.WorkerPoolThread/System.5	10.88.42.55:22222]	Stopping AsyncAgent Runtime.Scheduler.WorkerPoolThread/System.5 that runs on managed thread 10	
> [2017-04-20 22:52:23.176 GMT     9	WARNING	101222	Scheduler.ClientObserverRegistrar.WorkItemGroup	10.88.42.55:22222]	Thread <Runtime.Scheduler.WorkerPoolThread/3, ManagedThreadId=9, Executing WorkItem=System*WorkItemGroup:Name=ClientObserverRegistrar,WorkGroupStatus=Running Executing for 00:00:00.0050081. .> is exiting work loop due to cancellation token. WorkItemGroup: System*WorkItemGroup:Name=ClientObserverRegistrar,WorkGroupStatus=Running, Have 0 work items in the queue.	
> [2017-04-20 22:52:23.178 GMT     9	INFO   	100328	Runtime.Scheduler.WorkerPoolThread/3	10.88.42.55:22222]	Stopping AsyncAgent Runtime.Scheduler.WorkerPoolThread/3 that runs on managed thread 9	
> ...
> ... lots more lines
> ...
> SystemTarget..Current=3
> Watchdog.NumHealthChecks.Current=0
> 	
> [2017-04-20 22:52:23.284 GMT     5	INFO   	100294	SystemStatus	10.88.42.55:22222]	SystemStatus=Terminated	
> 
> 
> ------------------------------------------------------------------------
> log 2 - when viewing the 'Log Stream' page --
> ------------------------------------------------------------------------
> [2017-04-21 04:14:05.855 GMT    10	INFO   	100000	SiloControl	10.88.42.55:22222]	GetSimpleGrainStatistics	
> [2017-04-21 04:14:06.178 GMT    58	INFO   	100294	SystemStatus	10.88.42.55:22222]	SystemStatus=ShuttingDown	
> [2017-04-21 04:14:06.180 GMT    58	INFO   	100417	Silo	10.88.42.55:22222]	Silo starting to Shutdown()	
> [2017-04-21 04:14:06.182 GMT     6	INFO   	100606	MembershipOracle	10.88.42.55:22222]	-ShutDown	
> [2017-04-21 04:14:06.205 GMT     7	INFO   	102927	Orleans.Runtime.ReminderService.LocalReminderService	10.88.42.55:22222]	Stopping Orleans.Runtime.ReminderService.LocalReminderService grain service	
> [2017-04-21 04:14:06.211 GMT    58	INFO   	100545	Catalog	10.88.42.55:22222]	DeactivateAllActivations.	
> [2017-04-21 04:14:06.221 GMT    58	INFO   	100541	Catalog	10.88.42.55:22222]	DeactivateActivations: total 3 to shutdown, out of them 3 promptly, 0 later when become idle and 0 are already being destroyed or invalid.	
> [2017-04-21 04:14:06.227 GMT    58	INFO   	100503	Catalog	10.88.42.55:22222]	Starting DestroyActivations #0 of 3 activations	
> [2017-04-21 04:14:06.259 GMT    83	WARNING	100502	Catalog	10.88.42.55:22222]	UnregisterManyAsync 2 failed.	
> Exc level 0: System.InvalidOperationException: Grain directory is stopping
>    at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.CheckIfShouldForward(GrainId grainId, Int32 hopCount, String operationDescription)
>    at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.UnregisterOrPutInForwardList(IEnumerable`1 addresses, UnregistrationCause cause, Int32 hopCount, Dictionary`2& forward, List`1 tasks, String context)
>    at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.<UnregisterManyAsync>d__108.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Orleans.Runtime.Scheduler.SchedulerExtensions.<>c__DisplayClass1_0.<<QueueTask>b__0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Orleans.Runtime.Catalog.<FinishDestroyActivations>d__75.MoveNext()
> [2017-04-21 04:14:06.258 GMT     5	WARNING	100502	Catalog	10.88.42.55:22222]	UnregisterManyAsync 1 failed.	
> Exc level 0: System.InvalidOperationException: Grain directory is stopping
>    at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.CheckIfShouldForward(GrainId grainId, Int32 hopCount, String operationDescription)
>    at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.UnregisterOrPutInForwardList(IEnumerable`1 addresses, UnregistrationCause cause, Int32 hopCount, Dictionary`2& forward, List`1 tasks, String context)
>    at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.<UnregisterManyAsync>d__108.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Orleans.Runtime.Scheduler.SchedulerExtensions.<>c__DisplayClass1_0.<<QueueTask>b__0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Orleans.Runtime.Catalog.<FinishDestroyActivations>d__75.MoveNext()
> [2017-04-21 04:14:06.274 GMT    83	INFO   	101033	Dispatcher	10.88.42.55:22222]	Forwarding 1 requests to old address S10.88.42.55:22222:230444020*grn/FFE8F7B3/00000000@99c29dbc after Finished Destroy Activation.	
> ... NO FURTHER LOG LINES

**Comment by JasonGalea** [comment]
While I'm not seeing this exception, another colleague in another project has the same issue, however he sees the following exception.  Perhaps this is a place to start looking for the culprit?

> Grain directory is stopping
> Exception = System.InvalidOperationException: Grain directory is stopping
>    at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.CheckIfShouldForward(GrainId grainId, Int32 hopCount, String operationDescription)
>    at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.UnregisterOrPutInForwardList(IEnumerable`1 addresses, UnregistrationCause cause, Int32 hopCount, Dictionary`2& forward, List`1 tasks, String context)
>    at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.<UnregisterManyAsync>d__108.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Orleans.Runtime.Scheduler.SchedulerExtensions.<>c__DisplayClass1_0.<<QueueTask>b__0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Orleans.Runtime.Catalog.<FinishDestroyActivations>d__75.MoveNext()

**Comment by richorama** [comment]
Thanks for reporting this. I will investigate later today.

**Comment by richorama** [comment]
fixed by version 1.4.12
