### ISSUE TITLE
My dashboard can not show "Grain Details"

### ISSUE THREAD

**Issue by The-Naruto** [OrleansContrib/OrleansDashboard#431]
first, there is a lot of grains
![image](https://github.com/user-attachments/assets/b7688f17-c27f-4a9d-b22f-2c6f38b6519f)
but, i can't select anyone,
![image](https://github.com/user-attachments/assets/7e766ad1-68f9-4de9-81bc-0740d4717150)

**Comment by Dracarys7274** [comment]
thank you very much

> One of the things I was bitten by when trying out the dashboard: if your namespace starts with Orleans you won't be able to see it, unlikely but can happen. That will be fixed by #430

**Comment by The-Naruto** [comment]
> One of the things I was bitten by when trying out the dashboard: if your namespace starts with Orleans you won't be able to see it, unlikely but can happen. That will be fixed by #430
thank you !

**Comment by jkonecki** [comment]
Could you please provide the details of which version of Dashboard / Orleans are you using?

PS. 106 is not "a lot" ;-P

**Comment by Dracarys7274** [comment]
> Could you please provide the details of which version of Dashboard / Orleans are you using?
> 
> PS. 106 is not "a lot" ;-P

Thank's for your response,  My problem has been solved by Mr. Alrz, it is indeed a namespace issue!

The versions of Dashboard and Orleans are both 8.2.0.

Yes ,you are right, my English is quite poor and I am still learning    : )
