### ISSUE TITLE
Auto-scroll for Log Stream

### ISSUE THREAD

**Issue by DixonDs** [OrleansContrib/OrleansDashboard#44]
First of all, I love this new screen Log Stream, very useful! 

There is a minor improvement though that would be useful IMO - auto-scroll the view to show the latest logs always. I guess, it could be either the default behavior or some checkbox at the top

**Comment by richorama** [comment]
Hi @DixonDs, it should already autoscroll: 

https://github.com/OrleansContrib/OrleansDashboard/blob/master/App/components/log-stream.jsx#L12

...so I guess this isn't working for you.

What browser are you on?

**Comment by DixonDs** [comment]
Yes, it doesn't work in Firefox 53, but works in Chrome.

**Comment by richorama** [comment]
ah, ok, I'll download FF - thanks

**Comment by richorama** [comment]
fixed in version 1.4.8

**Comment by talarari** [comment]
a checkbox would be better IMO.
Currently its really hard to use the log stream since if i want to investigate something i have to copy paste the whole view to a text editor, because it keeps scrolling to the bottom and its impossible to scroll back up to look at the error.

**Comment by richorama** [comment]
@talarari I fixed a bug in b0350caff9be659d878b457f8f0393c02d34408c where the 'pause' button for the log stream could not be seen
