### ISSUE TITLE
Expose Dashboard via HTTPs endpoint

### ISSUE THREAD

**Issue by ponsakthi** [OrleansContrib/OrleansDashboard#45]
How do we securely expose this dashboard from an Azure cloud service using an https endpoint?

**Comment by richorama** [comment]
Hi @ponsakthi, you can add TLS in the usual way for cloud services: https://docs.microsoft.com/en-us/azure/cloud-services/cloud-services-configure-ssl-certificate

The dashboard also supports basic auth username and password.

I haven't tried it, but you could configure the firewall on the machines to restrict access by IP address: http://fabriccontroller.net/apply-ip-address-restrictions-to-your-windows-azure-cloud-services/

Please note that opening the dashboard to a public IP address does present an additional attack vector on your system. There are no known vulnerabilities. You do so at your own risk.
