### ISSUE TITLE
Add reminders view

### ISSUE THREAD

**Issue by DixonDs** [OrleansContrib/OrleansDashboard#51]
It would be beneficial, I think, to have another tab for reminders where you could see the list of them. Each entry could show the grain type, the grain key, the reminder name, its period and the next fire time. And finally, there could be Delete button to remove the selected reminder - it would be super helpful for orphaned reminders after grain refactoring.

**Comment by richorama** [comment]
Nice idea.

Any idea how you can query reminders?

**Comment by DixonDs** [comment]
Not really. I suppose you could use `IReminderTableGrain` (https://github.com/dotnet/orleans/blob/27b2a10a8c0dc44dfe839ae5fa638059828cd747/src/Orleans/SystemTargetInterfaces/IReminderTable.cs) if it was public. I think the best thing to do here is to ask in the main repo how to get that info and/or whether it is possible to make that grain public.

**Comment by richorama** [comment]
I wonder if there could be a scaling problem, a large number of reminders might kill the UI. Perhaps there is a way of grouping by grain type, or reminder frequency or something? What are your thoughts?

**Comment by DixonDs** [comment]
I was under impression that a large number of reminders is not desirable for the Orleans setup itself, but I think you are right, we need to handle it somehow. Maybe some kind of paging so that we don't return all reminders at once? Also I think the refresh period could be much larger, say once per minute or 5 minutes, or ideally defined by the user choice (a good example is a slider in Service Fabric explorer), as I don't expect reminders to be updated that often.

**Comment by DixonDs** [comment]
A few more things that would be good to add on top of what was done in https://github.com/OrleansContrib/OrleansDashboard/pull/56 :
1) Add grain implementation or interface type row to the reminders table - it would be handy to track orphaned reminders 
2) Add reminders view to the grain page with reminders associated with that grain.
3) Add Delete button to each reminder row.

Shall I add separate issues per each item for better tracking or is the current issue fine?

**Comment by richorama** [comment]
Good ideas.

w.r.t to the delete button, the dashboard (at the moment) is a readonly view, but I'm not opposed to adding a delete button. We could always add a switch to the config to enable/disable this feature.

Happy to keep just this issue for now.

**Comment by richorama** [comment]
I'm also thinking about a time-based view, like a calendar...
