### ISSUE TITLE
Orleans Dashboard on Service Fabric Host

### ISSUE THREAD

**Issue by pherbel** [OrleansContrib/OrleansDashboard#68]
Hi,
I got this when I tested the Dashborad With Orleans on Service Fabric.

How can I solve this issue?

Message": "[Error@127.0.0.1:30068@PID:7208] Caught and ignored exception: System.InvalidOperationException with mesagge: The current membership oracle does not support detailed silo status reporting. thrown from timer callback GrainTimer. TimerCallbackHandler:OrleansDashboard.DashboardGrain->System.Threading.Tasks.Task Callback(System.Object)
    Exception: System.InvalidOperationException: The current membership oracle does not support detailed silo status reporting.

All the help is appreciated

Thanks

**Comment by rikbosch** [comment]
@pherbel 
try using 
```csharp 
services.AddSingleton<ISiloDetailsProvider, SiloStatusOracleSiloDetailsProvider>();
```

in your startup.cs / configureservices method in the silo

**Comment by richorama** [comment]
There was an issue with this that got fixed in the 1.5.0 release I think. Could you confirm which version you're on?

Thanks.

**Comment by pherbel** [comment]
> services.AddSingleton<ISiloDetailsProvider, SiloStatusOracleSiloDetailsProvider>();

DI config was good. Now I don't get Exception.

But I can't access the UI endpoint.

I use this way:

`config.Globals.RegisterDashboard(Context.CodePackageActivationContext.GetEndpoint("OrleansDashboardEndpoint").Port,"admin","mapmatch");`

In service manifest:

`<Endpoint Name="OrleansDashboardEndpoint" Protocol="http" Type="Input" Port="8080" />`

**Comment by pherbel** [comment]
I could solve the issue and it was related to #62
