### ISSUE TITLE
OrleansDashboard.SiloGrain has called DeactivateOnIdle from within OnActivateAsync, which is not allowed.

### ISSUE THREAD

**Issue by amccool** [OrleansContrib/OrleansDashboard#7]
`[2016-06-01 00:36:53.369 GMT    11	ERROR  	100513	Catalog	172.18.124.93:11111]	
!!!!!!!!!! Error calling grain's OnActivateAsync() method - Grain type = OrleansDashboard.SiloGrain Activation = [Activation: S172.18.124.93:11111:202434420*grn/ACD5BA64/00000000+172.18.124.93:11111@202429561@6623488c #GrainType=OrleansDashboard.SiloGrain Placement=RandomPlacement State=Activating]	
`

`Exc level 0: System.InvalidOperationException: Activation [Activation: S172.18.124.93:11111:202434420*grn/ACD5BA64/00000000+172.18.124.93:11111@202429561@6623488c #GrainType=OrleansDashboard.SiloGrain Placement=RandomPlacement State=Activating] has called DeactivateOnIdle from within OnActivateAsync, which is not allowed.`

**Comment by richorama** [comment]
Interesting! Thanks, I'll take a look!

**Comment by richorama** [comment]
fixed
