### ISSUE TITLE
Publish .net core nuget packages

### ISSUE THREAD

**Issue by richorama** [OrleansContrib/OrleansDashboard#70]
I'm not sure quite how to go about this. Any help would be appreciated.

**Comment by rikbosch** [comment]
Might want to take a look at https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files

**Comment by DixonDs** [comment]
I would be much easier if the Orleans .Netstandard preview package was published on nuget.org, then we could just multi-target and have conditional package references for each platform. Probably that will still work if Orleans MyGet feed is added beforehand on the target machine trying to install the future .netstandard Orleans Dashboard package.

**Comment by creyke** [comment]
When Orleans is 2.0 we should they do this (it's in beta1 at time of writing).

At 2.0 it will be easy to publish a single standard package which can also be used in full.

**Comment by SebastianStehle** [comment]
I tried to migrate it, but ISiloStatusOracle is internal now :(

**Comment by richorama** [comment]
Shall I raise an issue on the Orleans repo?

**Comment by SebastianStehle** [comment]
I was wrong. It builds now. Very strange.

**Comment by SebastianStehle** [comment]
Solved in the 2.0 Branch
