### ISSUE TITLE
Allow filtering in log stream view

### ISSUE THREAD

**Issue by talarari** [OrleansContrib/OrleansDashboard#74]
Having a live tail view like the dashboard has in log stream is awesome.
Problem is its too noisy and its hard to find what you're looking for.
Adding a simple text/regex filter box in the view would make this much more useful.

**Comment by richorama** [comment]
Thanks for the suggestion.

There are a few things you can do currently that might help:

1. Adjust your logging level in configuration.
1. Use the built-in search feature in your browser.
1. Use curl on the command line to stream the log into grep.
1. Copy and paste the whole log stream into your own editor.

However I'll take a look at implementing this feature when I get a chance.

**Comment by richorama** [comment]
closed by #84
