### ISSUE TITLE
Remove dependencies

### ISSUE THREAD

**Issue by SebastianStehle** [OrleansContrib/OrleansDashboard#77]
Hi,

it looks awesome. But it would be nice if you can reduce the dependencies.

e.g.

* Use Middleware instead of controller.
* Allow hosting the UI everywhere, when you have at least a IGrainFactory
* Do not host Kestrel in the library.

I have Orleans and WebAPI running in the same process and it would give me much more flexibility if the UI and the statistics grains would be decoupled.

**Comment by richorama** [comment]
Hey @SebastianStehle,

Thanks for the suggestion. I'm open to PRs if you want to reorganise things, but one thing I'd like to maintain is the 'it just works' approach and keep it as easy as possible to install the dashboard.

I guess some of this could be achieved by making ketrel a configuration option (i.e. you can disable it with a setting).

Curious to hear your ideas...

**Comment by SebastianStehle** [comment]
Solved in the 2.0 Branch
