### ISSUE TITLE
Support for older Orleans releases

### ISSUE THREAD

**Issue by GadgetGeekUK** [OrleansContrib/OrleansDashboard#8]
Would it be possible to have a version that supports .NET 4.5 and Orleans 1.0.10.0 ?

I have had a go at downgrading it without success. The dashboard would be really useful in our environment.

**Comment by richorama** [comment]
Hi, the earliest version of Orleans that this dashboard goes back to is 1.1.0 

https://github.com/OrleansContrib/OrleansDashboard/blob/b952686cbb431ccff0590fea8929b41d01db7608/OrleansDashboard/packages.config#L6

I'm curious to know if you would consider upgrading to the latest Orleans? I think it would be difficult to maintain the dashboard for every Orleans release (although I'm not ruling it out) :¬/

**Comment by GadgetGeekUK** [comment]
I'm pushing for an upgrade, but it takes time...in the meantime we are stuck with 1.0.10 and .NET 4.5. I've been unable to downgrade your host to get it to work (the latest version worked straight out of the box). I then went on to follow the 'Minimal Orleans Application' example on the Orleans site only to find out that it doesn't work either. 
I got both to spool up a Silo Host, but when the 'GetGrain<Dashboard>' is called I get an exception saying the Grain Factory knows nothing about an implementation...

**Comment by GadgetGeekUK** [comment]
I've resolved the issues I had with the Grain Factory. I now have a working 1.0.10.0 version!

Maybe you could just mark the code with a 'Release' just prior to an Orleans version upgrade? No need to maintain them then, and people can go back to an earlier release without having to go down the rabbit hole like I did. ;)
