### ISSUE TITLE
Use github releases to share release notes

### ISSUE THREAD

**Issue by talarari** [OrleansContrib/OrleansDashboard#80]
I Update the package every once in a while, but i couldn't find release notes anywhere, or at least version tags on the source so i could browse through the commits...

makes it harder to trust the update.

**Comment by richorama** [comment]
ok, point taken. I'll start adding tags to the source code and making releases if that helps.

In the meantime you can see when the version number changes in this file: 

https://github.com/OrleansContrib/OrleansDashboard/commits/master/OrleansDashboard/OrleansDashboard.csproj

The code is released automatically when the version changes.

**Comment by talarari** [comment]
Great, thaks!
