### ISSUE TITLE
无法加载 DLL“libuv”: 找不到指定的模块

### ISSUE THREAD

**Issue by pandear** [OrleansContrib/OrleansDashboard#81]
System.DllNotFoundException: 无法加载 DLL“libuv”: 找不到指定的模块。 (异常来自 HRESULT:0x8007007E)。
   在 Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.NativeMethods.uv_loop_size()
   在 Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.loop_size()
   在 Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvLoopHandle.Init(Libuv uv)
   在 Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.ThreadStart(Object parameter)

How to do .

**Comment by richorama** [comment]
Sorry about this, there appears to be a problem with the kestrel library, it doesn't always use the correct version of libuv.dll.

Try copying the libuv dll into the bin folder (or including it in your project).

see issue #62

**Comment by pandear** [comment]
thanks very much.
