### ISSUE TITLE
Export metrics to standard metrics systems

### ISSUE THREAD

**Issue by talarari** [OrleansContrib/OrleansDashboard#85]
This dashboard is really great for looking at the cluster live, but its not that good at showing historical data and allowing analysis.

I think the best way to achieve this is to just report the metrics to a standard metics system like statsd or prometheus.

I'm working on a pull request to expose a prometheus metrics endpoint.
The basic concept is to just translate the data from the dashboard grain to a prometheus format endpoint.  

Would you be willing to accept a pull request when its done?

**Comment by richorama** [comment]
I agree with your analysis. The aim of the dashboard is to provide the developer a quick overview of the current system, and not attempt to be a Kafka/Grafana etc. 

I would be very happy to accept a PR for alternative endpoints. 

I assume you're planning on using the existing HTTP endpoint?

There is also a 2.0 branch of you would prefer to target the next version of Orleans. 

Thanks!

**Comment by SebastianStehle** [comment]
I am not sure if this is the responsibility of the dashboard. Orlans already provides extension points for that and it should be easy to graph the data and to push it to Elastic or RabbitMq or whatever.

**Comment by talarari** [comment]
@SebastianStehle i somewhat agree, but its kind of a gray zone.
I wouldn't want Orleans dashboard to start having multiple plugins to different metrics services, 
Since the dashboard is the one collecting the data (profiling grain calls, sampling silos etc), i think it might be a good feature to expose that in some way that does not complicate the api design does not add of a performance overhead.

Exporting a Prometheus (https://prometheus.io/) metrics endpoint kind of does that.
Since its a pull based metrics system all you need to do is export a text endpoint that shows the current state of your service, then you can point a Prometheus instance to it to collect data.

will looks something like this:
GET /metrics
```
# HELP orleans_activation_count 
# TYPE orleans_activation_count GAUGE
orleans_activation_count{grain_type="OrleansDashboard.SiloGrain",silo_address="127.0.0.1:24385@249727594"} 1

orleans_activation_count{grain_type="Orleans.Runtime.ReminderService.GrainBasedReminderTable",silo_address="127.0.0.1:24385@249727594"} 1

orleans_activation_count{grain_type="Orleans.Runtime.Management.ManagementGrain",silo_address="127.0.0.1:24385@249727594"} 1

orleans_activation_count{grain_type="OrleansDashboard.DashboardGrain",silo_address="127.0.0.1:24385@249727594"} 1

orleans_activation_count{grain_type="Orleans.Runtime.MembershipService.GrainBasedMembershipTable",silo_address="127.0.0.1:24385@249727594"} 1
```
 
Let me know what you guys think.

**Comment by SebastianStehle** [comment]
@talarari My point is that the dashboard aggregates the metrics in a way that it fits to the needs of the dashboard. This does not mean, that it is sufficient for your needs.

The most important class is:

https://github.com/OrleansContrib/OrleansDashboard/blob/2.0/OrleansDashboard/GrainProfiler.cs

I would just create one object for every grain call, and create a background thread to push it to elastic or another source (I would put RabbitMq between).

**Comment by talarari** [comment]
Im fine with the aggregations the dasboard does, i just want to have them historically and in a queryable way.
Again since prometheus is pull based, i dont need to puah anything to elastic/mq etc.
I just need to expose a rest api endpoint.

I can do this in another library by querying the dashboard grain or adding my own grain call interceptor.
I think this might be usefull for other people using orleans dashboard.

**Comment by shlomiw** [comment]
@talarari - what eventually did you end up with?
I'm also looking for historical metrics and connect to service such as statsd + graphene, or maybe other 3rd party metrics service.

**Comment by talarari** [comment]
Unfortunately didn't have the time to complete this

**Comment by SebastianStehle** [comment]
In Orleans 2.0 there is the TelemetryProducer with implementations for NewRelic and ApplicationInsights. I would just use this.
